using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Verce.Platform.Persistence;

namespace Verce.Modules.Commerce;

public sealed class ChannelOfferConfiguration : IEntityTypeConfiguration<ChannelOffer>
{ public void Configure(EntityTypeBuilder<ChannelOffer>b){b.ToTable("channel_offer","commerce",t=>{t.HasCheckConstraint("ck_channel_offer_price","intended_unit_price > 0");t.HasCheckConstraint("ck_channel_offer_shipping","seller_paid_shipping_amount IS NULL OR seller_paid_shipping_amount >= 0");t.HasCheckConstraint("ck_channel_offer_status","status IN ('ACTIVE','INACTIVE')");t.HasCheckConstraint("ck_channel_offer_price_source","price_source IN ('PRICING_ENGINE','MANUAL','IMPORTED_OBSERVED')");});b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Property(x=>x.Version).IsConcurrencyToken();b.HasApplicationMetadata();b.Property(x=>x.IntendedUnitPrice).HasColumnType("numeric(18,2)");b.Property(x=>x.SellerPaidShippingAmount).HasColumnType("numeric(18,2)");b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.PriceSource).HasConversion<string>().HasMaxLength(24);b.HasIndex(x=>new{x.ProductId,x.SalesChannelId}).IsUnique();b.HasIndex(x=>x.ProductId);b.HasIndex(x=>new{x.SalesChannelId,x.Status});}}
public sealed class MarketplaceProviderConfiguration:IEntityTypeConfiguration<MarketplaceProvider>{public void Configure(EntityTypeBuilder<MarketplaceProvider>b){b.ToTable("marketplace_provider","commerce");b.HasKey(x=>x.Code);b.Property(x=>x.Code).HasMaxLength(64);b.Property(x=>x.Name).HasMaxLength(100).IsRequired();}}
public sealed class MarketplaceProviderCapabilityConfiguration:IEntityTypeConfiguration<MarketplaceProviderCapability>{public void Configure(EntityTypeBuilder<MarketplaceProviderCapability>b){b.ToTable("marketplace_provider_capability","commerce",t=>t.HasCheckConstraint("ck_marketplace_provider_capability_state","state IN ('UNKNOWN','SUPPORTED','UNSUPPORTED')"));b.HasKey(x=>new{x.ProviderCode,x.CapabilityCode});b.Property(x=>x.ProviderCode).HasMaxLength(64);b.Property(x=>x.CapabilityCode).HasMaxLength(32);b.Property(x=>x.State).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.Source).HasMaxLength(16);b.HasOne<MarketplaceProvider>().WithMany().HasForeignKey(x=>x.ProviderCode).OnDelete(DeleteBehavior.Restrict);}}
public sealed class MarketplaceAccountConfiguration:IEntityTypeConfiguration<MarketplaceAccount>{public void Configure(EntityTypeBuilder<MarketplaceAccount>b){b.ToTable("marketplace_account","commerce",t=>{t.HasCheckConstraint("ck_marketplace_account_connection_state","connection_state IN ('NOT_CONFIGURED','DISCONNECTED','CONNECTED','ERROR')");t.HasCheckConstraint("ck_marketplace_account_sync_state","sync_state IN ('NEVER_SYNCED','SYNCED','ERROR')");});b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Property(x=>x.Version).IsConcurrencyToken();b.HasApplicationMetadata();b.Property(x=>x.ProviderCode).HasMaxLength(64);b.Property(x=>x.ExternalAccountId).HasMaxLength(200);b.Property(x=>x.DisplayName).HasMaxLength(200);b.Property(x=>x.CredentialReference).HasMaxLength(300);b.Property(x=>x.LastError).HasMaxLength(1000);b.Property(x=>x.ConnectionState).HasConversion<string>().HasMaxLength(24);b.Property(x=>x.SyncState).HasConversion<string>().HasMaxLength(16);b.HasIndex(x=>new{x.ProviderCode,x.ExternalAccountId}).IsUnique();b.HasIndex(x=>new{x.SalesChannelId,x.Active});b.HasIndex(x=>new{x.ProviderCode,x.Active});b.HasIndex(x=>x.SyncState);b.HasOne<MarketplaceProvider>().WithMany().HasForeignKey(x=>x.ProviderCode).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.Capabilities).WithOne().HasForeignKey(x=>x.MarketplaceAccountId).OnDelete(DeleteBehavior.Cascade);}}
public sealed class MarketplaceAccountCapabilityConfiguration:IEntityTypeConfiguration<MarketplaceAccountCapability>{public void Configure(EntityTypeBuilder<MarketplaceAccountCapability>b){b.ToTable("marketplace_account_capability","commerce",t=>t.HasCheckConstraint("ck_marketplace_account_capability_state","state IN ('UNKNOWN','GRANTED','DENIED')"));b.HasKey(x=>new{x.MarketplaceAccountId,x.CapabilityCode});b.Property(x=>x.CapabilityCode).HasMaxLength(32);b.Property(x=>x.State).HasConversion<string>().HasMaxLength(16);}}
public sealed class MarketplaceListingConfiguration:IEntityTypeConfiguration<MarketplaceListing>{public void Configure(EntityTypeBuilder<MarketplaceListing>b){b.ToTable("marketplace_listing","commerce",t=>{t.HasCheckConstraint("ck_marketplace_listing_linkage","(linkage_state = 'LINKED' AND product_id IS NOT NULL) OR (linkage_state IN ('UNLINKED','NEEDS_REVIEW') AND product_id IS NULL AND channel_offer_id IS NULL)");t.HasCheckConstraint("ck_marketplace_listing_offer_linkage","channel_offer_id IS NULL OR linkage_state = 'LINKED'");t.HasCheckConstraint("ck_marketplace_listing_observed_price","observed_price IS NULL OR observed_price > 0");});b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Property(x=>x.Version).IsConcurrencyToken();b.HasApplicationMetadata();b.Property(x=>x.ExternalListingId).HasMaxLength(200);b.Property(x=>x.ExternalSku).HasMaxLength(200);b.Property(x=>x.TitleSnapshot).HasMaxLength(500);b.Property(x=>x.ProviderNativeStatus).HasMaxLength(200);b.Property(x=>x.ListingUrl).HasMaxLength(2000);b.Property(x=>x.SyncError).HasMaxLength(1000);b.Property(x=>x.ObservedPrice).HasColumnType("numeric(18,2)");b.Property(x=>x.ObservedStatus).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.LinkageState).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.SyncState).HasConversion<string>().HasMaxLength(16);b.HasIndex(x=>new{x.MarketplaceAccountId,x.ExternalListingId}).IsUnique();b.HasIndex(x=>x.ProductId);b.HasIndex(x=>x.ChannelOfferId);b.HasIndex(x=>x.ObservedStatus);b.HasIndex(x=>x.LinkageState);b.HasIndex(x=>x.SyncState);b.HasIndex(x=>new{x.MarketplaceAccountId,x.ExternalSku});b.HasOne<MarketplaceAccount>().WithMany().HasForeignKey(x=>x.MarketplaceAccountId).OnDelete(DeleteBehavior.Restrict);b.HasOne<ChannelOffer>().WithMany().HasForeignKey(x=>x.ChannelOfferId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.Observations).WithOne().HasForeignKey(x=>x.MarketplaceListingId).OnDelete(DeleteBehavior.Cascade);b.HasMany(x=>x.Tags).WithOne().HasForeignKey(x=>x.MarketplaceListingId).OnDelete(DeleteBehavior.Cascade);}}
public sealed class MarketplaceListingObservationConfiguration:IEntityTypeConfiguration<MarketplaceListingObservation>{public void Configure(EntityTypeBuilder<MarketplaceListingObservation>b){b.ToTable("marketplace_listing_observation","commerce");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.HasApplicationMetadata();b.Property(x=>x.ExternalSku).HasMaxLength(200);b.Property(x=>x.TitleSnapshot).HasMaxLength(500);b.Property(x=>x.ObservedPrice).HasColumnType("numeric(18,2)");b.Property(x=>x.ObservedStatus).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.ProviderNativeStatus).HasMaxLength(200);b.Property(x=>x.ObservationKey).HasMaxLength(200);b.Property(x=>x.Fingerprint).HasMaxLength(128);b.Property(x=>x.Provenance).HasConversion<string>().HasMaxLength(16);b.HasIndex(x=>new{x.MarketplaceListingId,x.ObservationKey}).IsUnique();b.HasIndex(x=>new{x.MarketplaceListingId,x.ProviderObservedAt,x.IngestedAt});}}
public sealed class ProductCommercialProfileConfiguration:IEntityTypeConfiguration<ProductCommercialProfile>{public void Configure(EntityTypeBuilder<ProductCommercialProfile>b){b.ToTable("product_commercial_profile","commerce");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Property(x=>x.Version).IsConcurrencyToken();b.HasApplicationMetadata();b.HasIndex(x=>x.ProductId).IsUnique();b.HasMany(x=>x.Images).WithOne().HasForeignKey(x=>x.ProductCommercialProfileId).OnDelete(DeleteBehavior.Cascade);b.HasMany(x=>x.Tags).WithOne().HasForeignKey(x=>x.ProductCommercialProfileId).OnDelete(DeleteBehavior.Cascade);}}
public sealed class ProductCommercialImageConfiguration:IEntityTypeConfiguration<ProductCommercialImage>{public void Configure(EntityTypeBuilder<ProductCommercialImage>b){b.ToTable("product_commercial_image","commerce");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.HasApplicationMetadata();b.Property(x=>x.Role).HasConversion<string>().HasMaxLength(16);b.Property(x=>x.AltText).HasMaxLength(500);b.HasIndex(x=>new{x.ProductCommercialProfileId,x.BrandAssetId}).HasDatabaseName("ix_product_commercial_image_profile_asset").IsUnique();b.HasIndex(x=>new{x.ProductCommercialProfileId,x.SortOrder}).IsUnique();b.HasIndex(x=>x.ProductCommercialProfileId).HasFilter("role = 'PRIMARY'").IsUnique();}}
public sealed class CommercialTagConfiguration:IEntityTypeConfiguration<CommercialTag>{public void Configure(EntityTypeBuilder<CommercialTag>b){b.ToTable("commercial_tag","commerce");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Property(x=>x.Version).IsConcurrencyToken();b.HasApplicationMetadata();b.Property(x=>x.Code).HasMaxLength(64);b.Property(x=>x.Name).HasMaxLength(100);b.HasIndex(x=>x.Code).IsUnique();b.HasIndex(x=>x.Active);}}
public sealed class ProductCommercialTagConfiguration:IEntityTypeConfiguration<ProductCommercialTag>{public void Configure(EntityTypeBuilder<ProductCommercialTag>b){b.ToTable("product_commercial_tag","commerce");b.HasKey(x=>new{x.ProductCommercialProfileId,x.CommercialTagId});b.HasOne<CommercialTag>().WithMany().HasForeignKey(x=>x.CommercialTagId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class MarketplaceListingTagConfiguration:IEntityTypeConfiguration<MarketplaceListingTag>{public void Configure(EntityTypeBuilder<MarketplaceListingTag>b){b.ToTable("marketplace_listing_tag","commerce");b.HasKey(x=>new{x.MarketplaceListingId,x.CommercialTagId});b.HasOne<CommercialTag>().WithMany().HasForeignKey(x=>x.CommercialTagId).OnDelete(DeleteBehavior.Restrict);}}
