/**
 * M-S2-005: thin named aliases over the generated OpenAPI contract
 * (`./generated/schema.d.ts`, regenerated by `npm run api:generate` — never hand-edited).
 * Pages import from here instead of redeclaring API shapes by hand.
 */
import type { components } from './generated/schema'

type Schemas = components['schemas']

export type PersonType = Schemas['PersonType']
export type CustomerRequest = Schemas['CustomerRequest']
export type CustomerResponse = Schemas['CustomerResponse']
export type CustomerListItemResponse = Schemas['CustomerListItemResponse']
export type CustomerListResponse = Schemas['CustomerListResponse']
export type AddressRequest = Schemas['AddressRequest']
export type AddressResponse = Schemas['AddressResponse']
export type CompanyProfileResponse = Schemas['CompanyProfileResponse']
export type CompanyProfileRequest = Schemas['CompanyProfileRequest']
export type AppSettingResponse = Schemas['AppSettingResponse']
export type SettingUpdateRequest = Schemas['SettingUpdateRequest']
export type BrandAssetResponse = Schemas['BrandAssetResponse']
export type BrandAssetVersionResponse = Schemas['BrandAssetVersionResponse']
export type BrandAssetCreateRequest = Schemas['BrandAssetCreateRequest']
export type BrandAssetIdResponse = Schemas['BrandAssetIdResponse']
export type BrandActivationRequest = Schemas['BrandActivationRequest']
export type BrandingResponse = Schemas['BrandingResponse']
export type BrandingLogoResponse = Schemas['BrandingLogoResponse']

// ---- S3: Supplies & Inventory ----
export type SupplyBaseUnit = Schemas['SupplyBaseUnit']
export type FilamentMaterialType = Schemas['FilamentMaterialType']
export type FilamentDetailsRequest = Schemas['FilamentDetailsRequest']
export type FilamentDetailsResponse = Schemas['FilamentDetailsResponse']
export type SupplyCreateRequest = Schemas['SupplyCreateRequest']
export type SupplyUpdateRequest = Schemas['SupplyUpdateRequest']
export type SupplyResponse = Schemas['SupplyResponse']
export type SupplyListItemResponse = Schemas['SupplyListItemResponse']
export type SupplyListResponse = Schemas['SupplyListResponse']
export type SupplyCategoryResponse = Schemas['SupplyCategoryResponse']
export type InventoryMovementType = Schemas['InventoryMovementType']
export type InventoryAdjustmentKind = Schemas['InventoryAdjustmentKind']
export type SupplyListStatus = Schemas['SupplyListStatus']
export type InventorySummaryResponse = Schemas['InventorySummaryResponse']
export type InventoryMovementResponse = Schemas['InventoryMovementResponse']
export type InventoryMovementListResponse = Schemas['InventoryMovementListResponse']
export type InitialBalanceRequest = Schemas['InitialBalanceRequest']
export type PurchaseReceiptRequest = Schemas['PurchaseReceiptRequest']
export type InventoryAdjustmentRequest = Schemas['InventoryAdjustmentRequest']
