import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { CommercialCatalogPage } from './CommercialCatalogPage'

const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}));vi.mock('../api/client',()=>({apiClient:api}))
const state=vi.hoisted(()=>({roles:['Owner'] as string[]}));vi.mock('../auth/useSession',()=>({useSession:()=>({session:{status:'authenticated',user:{roles:state.roles}}})}))
const item={productId:'p1',code:'P1',name:'Produto 1',technicalActive:true,commercialActive:true,primaryImage:null,tags:[{id:'t1',code:'NATAL',name:'Natal'}],estimatedUnitCost:10,costCoverage:'PARTIAL_ESTIMATE',missingCostComponents:['ENERGY_UNAVAILABLE'],offers:[{id:'o1',salesChannelId:'c1',channelCode:'SHOPEE',channelName:'Shopee',channelKind:'Marketplace',status:'ACTIVE',intendedUnitPrice:30,priceSource:'MANUAL',sellerPaidShippingAmount:null,shippingState:'UNKNOWN',sales:{units:null,revenue:null,coverage:'UNKNOWN'},version:1}]}
function setup(){api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/catalog'))return Promise.resolve({ok:true,data:{items:[item],page:1,pageSize:12,total:1}});if(p.startsWith('/api/pricing/channels'))return Promise.resolve({ok:true,data:[{id:'c1',code:'SHOPEE',name:'Shopee',kind:'Marketplace',active:true}]});if(p==='/api/commerce/tags')return Promise.resolve({ok:true,data:item.tags});if(p==='/api/commerce/product-image-assets')return Promise.resolve({ok:true,data:[]});if(p.includes('/profiles/'))return Promise.resolve({ok:false,error:{safeMessage:'not found'}});return Promise.resolve({ok:true,data:[]})});api.post.mockResolvedValue({ok:true,data:{}});api.put.mockResolvedValue({ok:true,data:{}});api.delete.mockResolvedValue({ok:true,data:{}})}
function page(){return render(<MemoryRouter><CommercialCatalogPage/></MemoryRouter>)}
describe('CommercialCatalogPage',()=>{beforeEach(()=>{vi.clearAllMocks();state.roles=['Owner'];setup()})
  it('renders commercial state, unknown coverage and unavailable energy without zero placeholders',async()=>{page();expect(await screen.findByText(/P1 · Produto 1/)).toBeInTheDocument();expect(screen.getByText(/Vendas UNKNOWN — sem cobertura/)).toBeInTheDocument();expect(screen.getByText('Energia: indisponível')).toBeInTheDocument()})
  it('shows offer/profile controls to Owner and Operator',async()=>{const user=userEvent.setup();page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));expect(screen.getByRole('button',{name:'Salvar oferta'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Atribuir tag'})).toBeInTheDocument()})
  it('keeps Viewer read only',async()=>{state.roles=['Viewer'];const user=userEvent.setup();page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));expect(screen.queryByRole('button',{name:'Salvar oferta'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Atribuir tag'})).not.toBeInTheDocument()})
  it('renders only server-returned economics',async()=>{const user=userEvent.setup();api.post.mockResolvedValueOnce({ok:true,data:{estimatedProductCost:10,estimatedCommission:3,fixedFee:2,sellerPaidShippingAmount:null,netRevenue:25,estimatedProfit:15,contributionMargin:.5,markup:1.5,feeProvenance:'MANUAL',costCoverage:'PARTIAL_ESTIMATE',missingComponents:['ENERGY_UNAVAILABLE']}});page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));await user.click(screen.getByRole('button',{name:'Prévia econômica'}));await waitFor(()=>expect(screen.getByText((_,node)=>node?.tagName==='P'&&node.textContent?.includes('lucro')===true&&node.textContent.includes('15,00'))).toBeInTheDocument());expect(api.post).toHaveBeenCalledWith('/api/commerce/channel-economics/preview',expect.objectContaining({productId:'p1',salesChannelId:'c1'}))})
  it('sends filters and pagination to the server',async()=>{const user=userEvent.setup();api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/catalog'))return Promise.resolve({ok:true,data:{items:[item],page:p.includes('page=2')?2:1,pageSize:12,total:25}});if(p.startsWith('/api/pricing/channels'))return Promise.resolve({ok:true,data:[{id:'c1',code:'SHOPEE',name:'Shopee',kind:'Marketplace',active:true}]});if(p==='/api/commerce/tags')return Promise.resolve({ok:true,data:item.tags});return Promise.resolve({ok:true,data:[]})});page();await screen.findByText(/P1 · Produto 1/);await user.type(screen.getByLabelText('Buscar'),'Produto');await user.selectOptions(screen.getByLabelText('Comercial'),'true');await user.selectOptions(screen.getByLabelText('Canal'),'c1');await user.selectOptions(screen.getByLabelText('Tag'),'t1');await user.click(screen.getByRole('button',{name:'Filtrar'}));await waitFor(()=>expect(api.get).toHaveBeenCalledWith(expect.stringContaining('commercialActive=true')));expect(api.get).toHaveBeenCalledWith(expect.stringContaining('salesChannelId=c1'));expect(api.get).toHaveBeenCalledWith(expect.stringContaining('tagId=t1'));await user.click(screen.getByRole('button',{name:'Próxima'}));await waitFor(()=>expect(api.get).toHaveBeenCalledWith(expect.stringContaining('page=2')))})
  it('renders known marketplace sales as PARTIAL instead of COMPLETE',async()=>{api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/catalog'))return Promise.resolve({ok:true,data:{items:[{...item,offers:[{...item.offers[0],sales:{units:2,revenue:60,coverage:'PARTIAL'}}]}],page:1,pageSize:12,total:1}});if(p.startsWith('/api/pricing/channels'))return Promise.resolve({ok:true,data:[]});if(p==='/api/commerce/tags')return Promise.resolve({ok:true,data:[]});return Promise.resolve({ok:true,data:[]})});page();expect(await screen.findByText(/Vendas PARTIAL — 2 un./)).toBeInTheDocument()})
  it('creates or edits offers and toggles lifecycle through the API',async()=>{const user=userEvent.setup();const first=page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));await user.clear(screen.getByLabelText('Preço pretendido'));await user.type(screen.getByLabelText('Preço pretendido'),'32');await user.click(screen.getByRole('button',{name:'Salvar oferta'}));await waitFor(()=>expect(api.put).toHaveBeenCalledWith('/api/commerce/offers/o1',expect.objectContaining({intendedUnitPrice:32,sellerPaidShippingAmount:null})));first.unmount();page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));await user.click(screen.getByRole('button',{name:'Desativar'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/offers/o1/deactivate?version=1')})
  it('assigns and removes profile tags and PRODUCT_IMAGE assets',async()=>{const user=userEvent.setup();const profile={id:'pr1',productId:'p1',version:2,images:[{id:'i1',brandAssetId:'a1',role:'PRIMARY',sortOrder:0}],tagIds:['t1']};api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/catalog'))return Promise.resolve({ok:true,data:{items:[item],page:1,pageSize:12,total:1}});if(p.startsWith('/api/pricing/channels'))return Promise.resolve({ok:true,data:[]});if(p==='/api/commerce/tags')return Promise.resolve({ok:true,data:[...item.tags,{id:'t2',code:'NOVO',name:'Novo'}]});if(p==='/api/commerce/product-image-assets')return Promise.resolve({ok:true,data:[{id:'a1',name:'Atual',currentVersionId:'v1',url:'/a1'},{id:'a2',name:'Nova',currentVersionId:'v2',url:'/a2'}]});if(p.includes('/profiles/'))return Promise.resolve({ok:true,data:profile});return Promise.resolve({ok:true,data:[]})});page();await user.click(await screen.findByRole('button',{name:/P1 · Produto 1/}));await user.selectOptions(document.querySelector('#assign-tag') as HTMLSelectElement,'t2');await user.click(screen.getByRole('button',{name:'Atribuir tag'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/profiles/p1/tags/t2?version=2');await user.click(screen.getByRole('button',{name:'Remover Natal'}));expect(api.delete).toHaveBeenCalledWith('/api/commerce/profiles/p1/tags/t1?version=2');await user.selectOptions(screen.getByLabelText('Imagem PRODUCT_IMAGE'),'a2');await user.click(screen.getByRole('button',{name:'Atribuir imagem'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/profiles/p1/images',expect.objectContaining({brandAssetId:'a2',role:'GALLERY',sortOrder:1,version:2}));await user.click(screen.getByRole('button',{name:'Remover imagem'}));expect(api.delete).toHaveBeenCalledWith('/api/commerce/profiles/p1/images/i1?version=2')})
})
