import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { apiClient } from '../api/client'
import { useSession } from '../auth/useSession'

type Tag={id:string;code:string;name:string;active?:boolean;version?:number}
type Image={brandAssetId:string;versionId?:string;url:string;altText?:string}
type Sales={units:number|null;revenue:number|null;coverage:'COMPLETE'|'PARTIAL'|'UNKNOWN'}
type Offer={id:string;salesChannelId:string;channelCode:string;channelName:string;channelKind:string;status:'ACTIVE'|'INACTIVE';intendedUnitPrice:number;priceSource:string;sellerPaidShippingAmount:number|null;shippingState:string;sales:Sales;version:number}
type Item={productId:string;code:string;name:string;technicalActive:boolean;commercialActive:boolean;primaryImage:Image|null;tags:Tag[];estimatedUnitCost:number|null;costCoverage:string;missingCostComponents:string[];offers:Offer[]}
type Catalog={items:Item[];page:number;pageSize:number;total:number}
type Channel={id:string;code:string;name:string;kind:string;active:boolean}
type Asset={id:string;name:string;currentVersionId:string;url:string}
type Profile={id:string;productId:string;version:number;images:{id:string;brandAssetId:string;role:string;sortOrder:number;altText?:string}[];tagIds:string[]}
type Economics={estimatedProductCost:number;estimatedCommission:number;fixedFee:number;sellerPaidShippingAmount:number|null;netRevenue:number;estimatedProfit:number;contributionMargin:number;markup:number;feeProvenance:string;costCoverage:string;estimateClassification:string;missingComponents:string[];comparisonQuantity:number;fixedFeeApplication:string;costBasis:string;feeObservedAt:string|null;feeExpiresAt:string|null;packagingComponent:number|null}

const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function CommercialCatalogPage(){
  const {session}=useSession(); const roles=session.status==='authenticated'?session.user.roles:[]; const canManage=roles.includes('Owner')||roles.includes('Operator')
  const [data,setData]=useState<Catalog|null>(null); const [channels,setChannels]=useState<Channel[]>([]); const [tags,setTags]=useState<Tag[]>([]); const [assets,setAssets]=useState<Asset[]>([])
  const [search,setSearch]=useState(''); const [active,setActive]=useState(''); const [commercial,setCommercial]=useState(''); const [channelId,setChannelId]=useState(''); const [tagId,setTagId]=useState(''); const [page,setPage]=useState(1); const [message,setMessage]=useState('')
  const [selected,setSelected]=useState<Item|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [offerChannel,setOfferChannel]=useState(''); const [price,setPrice]=useState(''); const [shipping,setShipping]=useState(''); const [economics,setEconomics]=useState<Record<string,Economics>>({}); const [assignTag,setAssignTag]=useState(''); const [assignAsset,setAssignAsset]=useState('')
  const load=useCallback(async()=>{const q=new URLSearchParams({page:String(page),pageSize:'12'});if(search)q.set('search',search);if(active)q.set('active',active);if(commercial)q.set('commercialActive',commercial);if(channelId)q.set('salesChannelId',channelId);if(tagId)q.set('tagId',tagId);const r=await apiClient.get<Catalog>(`/api/commerce/catalog?${q}`);if(r.ok)setData(r.data);else setMessage(r.error.safeMessage)},[page,search,active,commercial,channelId,tagId])
  const loadReferences=useCallback(async()=>{const [c,t,a]=await Promise.all([apiClient.get<Channel[]>('/api/pricing/channels?includeInactive=false'),apiClient.get<Tag[]>('/api/commerce/tags'),apiClient.get<Asset[]>('/api/commerce/product-image-assets')]);if(c.ok)setChannels(c.data);if(t.ok)setTags(t.data);if(a.ok)setAssets(a.data)},[])
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();void loadReferences()},0);return()=>window.clearTimeout(timer)},[load,loadReferences])
  async function refreshProfile(productId:string){const r=await apiClient.get<Profile>(`/api/commerce/profiles/${productId}`);setProfile(r.ok?r.data:null)}
  async function open(item:Item){setSelected(item);setOfferChannel(item.offers[0]?.salesChannelId??'');setPrice(item.offers[0]?.intendedUnitPrice?.toString()??'');setShipping(item.offers[0]?.sellerPaidShippingAmount?.toString()??'');await refreshProfile(item.productId)}
  function chooseOffer(channel:string){setOfferChannel(channel);const o=selected?.offers.find(x=>x.salesChannelId===channel);setPrice(o?.intendedUnitPrice.toString()??'');setShipping(o?.sellerPaidShippingAmount?.toString()??'')}
  async function saveOffer(e:FormEvent){e.preventDefault();if(!selected||!offerChannel)return;const existing=selected.offers.find(x=>x.salesChannelId===offerChannel);const body={productId:selected.productId,salesChannelId:offerChannel,intendedUnitPrice:Number(price),priceSource:'MANUAL',sellerPaidShippingAmount:shipping.trim()===''?null:Number(shipping),version:existing?.version??null};const r=existing?await apiClient.put<void>(`/api/commerce/offers/${existing.id}`,body):await apiClient.post<void>('/api/commerce/offers',body);setMessage(r.ok?'Oferta salva.':r.error.safeMessage);if(r.ok){await load();setSelected(null)}}
  async function toggleOffer(offer:Offer){const action=offer.status==='ACTIVE'?'deactivate':'activate';const r=await apiClient.post<void>(`/api/commerce/offers/${offer.id}/${action}?version=${offer.version}`);setMessage(r.ok?`Oferta ${action==='activate'?'ativada':'desativada'}.`:r.error.safeMessage);if(r.ok)await load()}
  async function preview(offer:Offer){if(!selected)return;const r=await apiClient.post<Economics>('/api/commerce/channel-economics/preview',{productId:selected.productId,salesChannelId:offer.salesChannelId,intendedUnitPrice:offer.intendedUnitPrice,sellerPaidShippingAmount:offer.sellerPaidShippingAmount});if(r.ok)setEconomics({...economics,[offer.id]:r.data});else setMessage(r.error.safeMessage)}
  async function addTag(){if(!selected||!assignTag)return;const r=await apiClient.post<void>(`/api/commerce/profiles/${selected.productId}/tags/${assignTag}?version=${profile?.version??0}`);setMessage(r.ok?'Tag atribuída.':r.error.safeMessage);if(r.ok){await refreshProfile(selected.productId);await load()}}
  async function removeTag(id:string){if(!selected||!profile)return;const r=await apiClient.delete<void>(`/api/commerce/profiles/${selected.productId}/tags/${id}?version=${profile.version}`);setMessage(r.ok?'Tag removida.':r.error.safeMessage);if(r.ok){await refreshProfile(selected.productId);await load()}}
  async function addImage(){if(!selected||!assignAsset)return;const r=await apiClient.post<void>(`/api/commerce/profiles/${selected.productId}/images`,{brandAssetId:assignAsset,role:profile?.images.length?'GALLERY':'PRIMARY',sortOrder:profile?.images.length??0,altText:selected.name,version:profile?.version??0});setMessage(r.ok?'Imagem atribuída.':r.error.safeMessage);if(r.ok){await refreshProfile(selected.productId);await load()}}
  async function removeImage(id:string){if(!selected||!profile)return;const r=await apiClient.delete<void>(`/api/commerce/profiles/${selected.productId}/images/${id}?version=${profile.version}`);setMessage(r.ok?'Imagem removida.':r.error.safeMessage);if(r.ok){await refreshProfile(selected.productId);await load()}}
  return <section className="product-page"><div className="page-heading"><div><Link to="/">← Início</Link><h1>Catálogo Comercial</h1><p>Produtos, intenção comercial, custo estimado e cobertura de vendas registrada.</p></div></div>
    <form className="card inline-form" onSubmit={e=>{e.preventDefault();setPage(1);void load()}}><label htmlFor="catalog-search">Buscar</label><input id="catalog-search" value={search} onChange={e=>setSearch(e.target.value)}/><label htmlFor="catalog-active">Produto</label><select id="catalog-active" value={active} onChange={e=>setActive(e.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select><label htmlFor="catalog-commercial">Comercial</label><select id="catalog-commercial" value={commercial} onChange={e=>setCommercial(e.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Sem oferta ativa</option></select><label htmlFor="catalog-channel">Canal</label><select id="catalog-channel" value={channelId} onChange={e=>setChannelId(e.target.value)}><option value="">Todos</option>{channels.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><label htmlFor="catalog-tag">Tag</label><select id="catalog-tag" value={tagId} onChange={e=>setTagId(e.target.value)}><option value="">Todas</option>{tags.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button type="submit">Filtrar</button></form>
    {message&&<p role="status">{message}</p>}<div className="card"><p>{data?.total??0} produto(s)</p><ul className="data-list">{data?.items.map(item=><li key={item.productId}>{item.primaryImage&&<img src={item.primaryImage.url} alt={item.primaryImage.altText??item.name} width="72" height="72"/>}<button type="button" onClick={()=>void open(item)}><strong>{item.code} · {item.name}</strong></button><span className={item.technicalActive?'badge':'badge badge--muted'}>{item.technicalActive?'Técnico ativo':'Técnico inativo'}</span><span className={item.commercialActive?'badge':'badge badge--muted'}>{item.commercialActive?'Comercial ativo':'Sem oferta ativa'}</span><span>Custo: {item.estimatedUnitCost==null?'Indisponível':money(item.estimatedUnitCost)} ({item.costCoverage})</span><span>Energia: indisponível</span><span>Tags: {item.tags.map(x=>x.name).join(', ')||'nenhuma'}</span>{item.offers.map(o=><span key={o.id}>{o.channelCode}: {money(o.intendedUnitPrice)} · {o.status} · Frete {o.shippingState==='UNKNOWN'?'desconhecido':money(o.sellerPaidShippingAmount??0)} · Vendas {o.sales.coverage}{o.sales.units==null?' — sem cobertura':` — ${o.sales.units} un. / ${money(o.sales.revenue??0)}`}{o.channelKind==='Direct'?' · cobertura completa para vendas registradas no VERCE':''}</span>)}</li>)}</ul>
      <div className="inline-form"><button type="button" disabled={(data?.page??1)<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Anterior</button><span>Página {data?.page??1}</span><button type="button" disabled={!data||data.page*data.pageSize>=data.total} onClick={()=>setPage(x=>x+1)}>Próxima</button></div></div>
    {selected&&<div className="split-grid"><div className="card"><h2>{selected.name}</h2><h3>Ofertas</h3>{selected.offers.map(o=><div key={o.id}><p>{o.channelName}: {money(o.intendedUnitPrice)} ({o.status})</p><button type="button" onClick={()=>void preview(o)}>Prévia econômica</button>{canManage&&<button type="button" onClick={()=>void toggleOffer(o)}>{o.status==='ACTIVE'?'Desativar':'Ativar'}</button>}{economics[o.id]&&<p>{economics[o.id].estimateClassification==='PARTIAL_ESTIMATE'?'Estimativa parcial · ':''}{economics[o.id].missingComponents.includes('SHIPPING')?'Frete não informado · ':''}Custo {money(economics[o.id].estimatedProductCost)} · taxas {money(economics[o.id].estimatedCommission+economics[o.id].fixedFee)} · lucro {money(economics[o.id].estimatedProfit)} · margem {(economics[o.id].contributionMargin*100).toFixed(2)}% · {economics[o.id].feeProvenance} · Energia indisponível</p>}</div>)}{canManage&&<form className="form-stack" onSubmit={saveOffer}><h3>Criar ou editar oferta</h3><label htmlFor="offer-channel">Canal</label><select id="offer-channel" required value={offerChannel} onChange={e=>chooseOffer(e.target.value)}><option value="">Selecione</option>{channels.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label htmlFor="offer-price">Preço pretendido</label><input id="offer-price" required type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/><label htmlFor="offer-shipping">Frete pago pelo vendedor</label><input id="offer-shipping" type="number" min="0" step="0.01" value={shipping} onChange={e=>setShipping(e.target.value)} placeholder="Desconhecido"/><button type="submit">Salvar oferta</button></form>}</div>
      <div className="card"><h2>Perfil comercial</h2><p>Tags atribuídas: {profile?.tagIds.map(id=>tags.find(x=>x.id===id)?.name??id).join(', ')||'nenhuma'}</p>{canManage&&<><label htmlFor="assign-tag">Tag</label><select id="assign-tag" value={assignTag} onChange={e=>setAssignTag(e.target.value)}><option value="">Selecione</option>{tags.filter(x=>x.active!==false&&!profile?.tagIds.includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button type="button" onClick={()=>void addTag()}>Atribuir tag</button>{profile?.tagIds.map(id=><button key={id} type="button" onClick={()=>void removeTag(id)}>Remover {tags.find(x=>x.id===id)?.name??'tag'}</button>)}<label htmlFor="assign-image">Imagem PRODUCT_IMAGE</label><select id="assign-image" value={assignAsset} onChange={e=>setAssignAsset(e.target.value)}><option value="">Selecione</option>{assets.filter(x=>!profile?.images.some(i=>i.brandAssetId===x.id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button type="button" onClick={()=>void addImage()}>Atribuir imagem</button>{profile?.images.map(i=><div key={i.id}><span>{i.role} · ordem {i.sortOrder}</span><button type="button" onClick={()=>void removeImage(i.id)}>Remover imagem</button></div>)}</>}</div></div>}
  </section>
}
