import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { MarketplaceAccountsPage } from './MarketplaceAccountsPage'
const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}));vi.mock('../api/client',()=>({apiClient:api}))
const state=vi.hoisted(()=>({roles:['Owner'] as string[]}));vi.mock('../auth/useSession',()=>({useSession:()=>({session:{status:'authenticated',user:{roles:state.roles}}})}))
function setup(){api.get.mockImplementation((p:string)=>{if(p==='/api/commerce/marketplace-accounts')return Promise.resolve({ok:true,data:[{id:'a1',providerCode:'SHOPEE',externalAccountId:'shop',salesChannelId:'c1',displayName:'Loja',active:true,connectionState:'NOT_CONFIGURED',syncState:'NEVER_SYNCED',version:1,capabilities:[{capabilityCode:'LISTINGS_READ',state:'UNKNOWN'}]}]});if(p==='/api/commerce/providers')return Promise.resolve({ok:true,data:[{code:'SHOPEE',name:'Shopee',capabilities:[]}]});return Promise.resolve({ok:true,data:[{id:'c1',code:'SHOP',name:'Shopee',kind:'Marketplace',active:true}]})});api.post.mockResolvedValue({ok:true,data:{}});api.put.mockResolvedValue({ok:true,data:{}})}
describe('MarketplaceAccountsPage',()=>{beforeEach(()=>{vi.clearAllMocks();state.roles=['Owner'];setup()})
  it('shows lifecycle controls to Owner',async()=>{render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);expect(await screen.findByRole('button',{name:'Nova conta'})).toBeInTheDocument();expect(screen.getByText(/LISTINGS_READ: UNKNOWN/)).toBeInTheDocument()})
  it('keeps Operator account administration read only',async()=>{state.roles=['Operator'];render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);expect(await screen.findByText(/LISTINGS_READ: UNKNOWN/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Nova conta'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Salvar conta'})).not.toBeInTheDocument()})
  it('keeps Viewer account administration read only',async()=>{state.roles=['Viewer'];render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);expect(await screen.findByText(/LISTINGS_READ: UNKNOWN/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Nova conta'})).not.toBeInTheDocument()})
  it('lets Owner create and deactivate an account through backend APIs',async()=>{const user=userEvent.setup();const first=render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Nova conta'}));await user.selectOptions(screen.getByLabelText('Provedor'),'SHOPEE');await user.type(screen.getByLabelText('Identidade externa'),'new-shop');await user.selectOptions(screen.getByLabelText('Canal'),'c1');await user.type(screen.getByLabelText('Nome de exibição'),'Nova Loja');await user.click(screen.getByRole('button',{name:'Salvar conta'}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts',expect.objectContaining({providerCode:'SHOPEE',externalAccountId:'new-shop',salesChannelId:'c1',displayName:'Nova Loja'})));first.unmount();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));await user.click(screen.getByRole('button',{name:'Desativar conta'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/deactivate?version=1')})
})
