import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { apiClient } from '../api/client'
import { useSession } from '../auth/useSession'

type Capability={capabilityCode:string;state:string}
type Account={id:string;providerCode:string;externalAccountId:string;salesChannelId:string;displayName:string;active:boolean;connectionState:string;syncState:string;version:number;capabilities:Capability[]}
type Provider={code:string;name:string;capabilities:{capabilityCode:string;state:string}[]}
type Channel={id:string;code:string;name:string;kind:string;active:boolean}
type Form={providerCode:string;externalAccountId:string;salesChannelId:string;displayName:string;credentialReference:string}
const blank:Form={providerCode:'',externalAccountId:'',salesChannelId:'',displayName:'',credentialReference:''}

export function MarketplaceAccountsPage(){
  const {session}=useSession();const isOwner=session.status==='authenticated'&&session.user.roles.includes('Owner')
  const [items,setItems]=useState<Account[]>([]);const [providers,setProviders]=useState<Provider[]>([]);const [channels,setChannels]=useState<Channel[]>([]);const [selected,setSelected]=useState<Account|null>(null);const [form,setForm]=useState<Form>(blank);const [message,setMessage]=useState('')
  const load=useCallback(async()=>{const [a,p,c]=await Promise.all([apiClient.get<Account[]>('/api/commerce/marketplace-accounts'),apiClient.get<Provider[]>('/api/commerce/providers'),apiClient.get<Channel[]>('/api/pricing/channels?includeInactive=false')]);if(a.ok)setItems(a.data);else setMessage(a.error.safeMessage);if(p.ok)setProviders(p.data);if(c.ok)setChannels(c.data.filter(x=>x.kind==='Marketplace'&&x.code!=='DIRECT'))},[])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  function choose(item:Account){setSelected(item);setForm({providerCode:item.providerCode,externalAccountId:item.externalAccountId,salesChannelId:item.salesChannelId,displayName:item.displayName,credentialReference:''})}
  function fresh(){setSelected(null);setForm(blank)}
  async function save(e:FormEvent){e.preventDefault();const body={...form,credentialReference:form.credentialReference||null,version:selected?.version??null};const r=selected?await apiClient.put<void>(`/api/commerce/marketplace-accounts/${selected.id}`,body):await apiClient.post<void>('/api/commerce/marketplace-accounts',body);setMessage(r.ok?'Conta salva.':r.error.safeMessage);if(r.ok){fresh();await load()}}
  async function toggle(){if(!selected)return;const action=selected.active?'deactivate':'activate';const r=await apiClient.post<void>(`/api/commerce/marketplace-accounts/${selected.id}/${action}?version=${selected.version}`);setMessage(r.ok?`Conta ${selected.active?'desativada':'ativada'}.`:r.error.safeMessage);if(r.ok){fresh();await load()}}
  return <section className="product-page"><div className="page-heading"><div><Link to="/">← Início</Link><h1>Contas de Marketplace</h1><p>Configuração local e capacidades estruturais. Não há OAuth nem conexão externa no S8B.</p></div>{isOwner&&<button type="button" onClick={fresh}>Nova conta</button>}</div>{message&&<p role="status">{message}</p>}
    <div className="split-grid"><div className="card"><ul className="data-list">{items.map(x=><li key={x.id}><button type="button" onClick={()=>choose(x)}><strong>{x.displayName}</strong></button><span>{x.providerCode} · {x.externalAccountId}</span><span>Canal: {channels.find(c=>c.id===x.salesChannelId)?.name??x.salesChannelId}</span><span className={x.active?'badge':'badge badge--muted'}>{x.active?'Ativa':'Inativa'}</span><span>Conexão: {x.connectionState}; sincronização: {x.syncState}</span><span>Capacidades: {x.capabilities.map(c=>`${c.capabilityCode}: ${c.state}`).join(', ')||'não configuradas'}</span></li>)}{items.length===0&&<li>Nenhuma conta local configurada.</li>}</ul></div>
      {isOwner&&<form className="card form-stack" onSubmit={save}><h2>{selected?'Editar conta':'Nova conta'}</h2><label htmlFor="account-provider">Provedor</label><select id="account-provider" required disabled={!!selected} value={form.providerCode} onChange={e=>setForm({...form,providerCode:e.target.value})}><option value="">Selecione</option>{providers.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select><label htmlFor="account-external">Identidade externa</label><input id="account-external" required disabled={!!selected} value={form.externalAccountId} onChange={e=>setForm({...form,externalAccountId:e.target.value})}/><label htmlFor="account-channel">Canal</label><select id="account-channel" required disabled={!!selected} value={form.salesChannelId} onChange={e=>setForm({...form,salesChannelId:e.target.value})}><option value="">Selecione</option>{channels.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><label htmlFor="account-name">Nome de exibição</label><input id="account-name" required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/><label htmlFor="account-credential">Referência opaca de credencial</label><input id="account-credential" value={form.credentialReference} onChange={e=>setForm({...form,credentialReference:e.target.value})} placeholder={selected?'Deixe vazio para remover':'Opcional'}/><button type="submit">Salvar conta</button>{selected&&<button type="button" onClick={()=>void toggle()}>{selected.active?'Desativar':'Ativar'} conta</button>}</form>}</div>
  </section>
}
