import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { MarketplaceAccountsPage } from './MarketplaceAccountsPage'
const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}));vi.mock('../api/client',()=>({apiClient:api}))
const state=vi.hoisted(()=>({roles:['Owner'] as string[]}));vi.mock('../auth/useSession',()=>({useSession:()=>({session:{status:'authenticated',user:{roles:state.roles}}})}))
const connectionStatus=vi.hoisted(()=>({current:{accountId:'a1',authorizationState:'CONNECTED',runtimeAvailability:'AVAILABLE',identityVerifiedAt:'2026-01-01T00:00:00Z',lastSuccessAt:'2026-01-02T00:00:00Z',lastFailureAt:null as string|null,lastFailureClassification:null as string|null,requiredAction:'NONE',authorizationInProgress:false,credentialOperationInProgress:false,version:1}}))
function setup(){api.get.mockImplementation((p:string)=>{if(p==='/api/commerce/marketplace-accounts')return Promise.resolve({ok:true,data:[{id:'a1',providerCode:'SHOPEE',externalAccountId:'shop',salesChannelId:'c1',displayName:'Loja',active:true,authorizationState:'CONNECTED',runtimeAvailability:'AVAILABLE',syncState:'NEVER_SYNCED',version:1,capabilities:[{capabilityCode:'LISTINGS_READ',state:'GRANTED'}]}]});if(p==='/api/commerce/providers')return Promise.resolve({ok:true,data:[{code:'SHOPEE',name:'Shopee',capabilities:[]}]});if(p==='/api/commerce/marketplace-accounts/a1/connection')return Promise.resolve({ok:true,data:connectionStatus.current});return Promise.resolve({ok:true,data:[{id:'c1',code:'SHOP',name:'Shopee',kind:'Marketplace',active:true}]})});api.post.mockResolvedValue({ok:true,data:{sessionId:'s1',expiresAt:'2026-01-01T00:00:00Z',authorizationUri:'https://provider.example/authorize'}});api.put.mockResolvedValue({ok:true,data:{}})}
describe('MarketplaceAccountsPage',()=>{beforeEach(()=>{vi.clearAllMocks();state.roles=['Owner'];connectionStatus.current={accountId:'a1',authorizationState:'CONNECTED',runtimeAvailability:'AVAILABLE',identityVerifiedAt:'2026-01-01T00:00:00Z',lastSuccessAt:'2026-01-02T00:00:00Z',lastFailureAt:null,lastFailureClassification:null,requiredAction:'NONE',authorizationInProgress:false,credentialOperationInProgress:false,version:1};setup()})
  it('shows authorization state and lifecycle controls to Owner',async()=>{render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);expect(await screen.findByRole('button',{name:'Conectar conta'})).toBeInTheDocument();expect(screen.getByText(/LISTINGS_READ: GRANTED/)).toBeInTheDocument()})
  it('keeps Operator account administration read only',async()=>{state.roles=['Operator'];render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);expect(await screen.findByText(/LISTINGS_READ: GRANTED/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Conectar conta'})).not.toBeInTheDocument()})
  it('starts authorization without collecting an external identity or credential',async()=>{const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await screen.findByRole('option',{name:'Shopee'});api.post.mockResolvedValueOnce({ok:false,error:{safeMessage:'provider unavailable'}});await user.selectOptions(screen.getByLabelText('Provedor'),'SHOPEE');await user.selectOptions(screen.getByLabelText('Canal'),'c1');await user.type(screen.getByLabelText('Nome de exibição'),'Nova Loja');await user.click(screen.getByRole('button',{name:'Autorizar com provedor'}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-authorizations',{providerCode:'SHOPEE',salesChannelId:'c1',displayName:'Nova Loja'}));expect(screen.queryByLabelText(/Identidade externa/)).not.toBeInTheDocument();expect(screen.queryByLabelText(/credencial/i)).not.toBeInTheDocument()})
  it('uses dedicated reauthorization and disconnect endpoints',async()=>{const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));api.post.mockResolvedValueOnce({ok:false,error:{safeMessage:'provider unavailable'}});await user.click(screen.getByRole('button',{name:'Reautorizar'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/reauthorize',{version:1});await user.click(screen.getByRole('button',{name:'Desconectar conta'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/disconnect',{version:1})})

  it('shows safe status detail (identity verified, last success, no secret fields) after selecting an account',async()=>{const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));expect(await screen.findByText(/Último sucesso/)).toBeInTheDocument();expect(screen.getByText(/Identidade verificada em/)).toBeInTheDocument();const html=document.body.innerHTML;expect(html).not.toMatch(/credentialReference/i);expect(html).not.toMatch(/stateHash/i);expect(html).not.toMatch(/browserBindingHash/i);expect(html).not.toMatch(/access.?token/i);expect(html).not.toMatch(/refresh.?token/i)})

  it('offers an explicit Probe action that calls the dedicated endpoint',async()=>{const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));await user.click(await screen.findByRole('button',{name:'Sondar disponibilidade'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/probe',{version:1})})

  it('shows a distinct RECONNECT_EXISTING_ACCOUNT prompt and reuses the reauthorize route for it',async()=>{connectionStatus.current={...connectionStatus.current,requiredAction:'RECONNECT_EXISTING_ACCOUNT'};const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));expect(await screen.findByText(/MESMA conta no provedor/)).toBeInTheDocument();const reconnectButton=screen.getByRole('button',{name:'Reconectar conta existente'});await user.click(reconnectButton);expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/reauthorize',{version:1})})

  it('shows a distinct REAUTHORIZE_AFTER_STORE_LOSS prompt without deleting the account, and reuses the reauthorize route',async()=>{connectionStatus.current={...connectionStatus.current,authorizationState:'REAUTHORIZATION_REQUIRED',requiredAction:'REAUTHORIZE_AFTER_STORE_LOSS'};const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));expect(await screen.findByText(/perda de armazenamento\/chave/)).toBeInTheDocument();const recoverButton=screen.getByRole('button',{name:'Recuperar credencial (reautorizar)'});await user.click(recoverButton);expect(api.post).toHaveBeenCalledWith('/api/commerce/marketplace-accounts/a1/reauthorize',{version:1});expect(screen.getByRole('button',{name:'Loja'})).toBeInTheDocument()})

  it('lets Operator see safe status detail read-only without any configuration/credential action',async()=>{state.roles=['Operator'];const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));expect(await screen.findByText(/Último sucesso/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Reautorizar'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Sondar disponibilidade'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Desconectar conta'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Ativar conta'})).not.toBeInTheDocument()})

  it('lets Viewer see safe status detail read-only without any configuration/credential action',async()=>{state.roles=['Viewer'];const user=userEvent.setup();render(<MemoryRouter><MarketplaceAccountsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Loja'}));expect(await screen.findByText(/Último sucesso/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Reautorizar'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Sondar disponibilidade'})).not.toBeInTheDocument()})
})
