import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient } from '../api/client'
import { useSession } from '../auth/useSession'

type Listing={id:string;providerCode:string;marketplaceAccountId:string;accountName:string;salesChannelId:string;channelCode:string;channelName:string;externalListingId:string;externalSku?:string;title?:string;observedPrice?:number;observedStatus:string;productId?:string;productCode?:string;productName?:string;channelOfferId?:string;linkageState:string;syncState:string;lastObservedAt?:string;lastSyncAttemptAt?:string;lastSuccessfulSyncAt?:string;safeSyncError?:string;version:number}
type Response={items:Listing[];page:number;pageSize:number;total:number}
type Account={id:string;providerCode:string;displayName:string;salesChannelId:string}
type Product={id:string;code:string;name:string}
type ProductResponse={items:Product[]}
type Offer={id:string;productId:string;salesChannelId:string;status:string;intendedUnitPrice:number}
type OfferResponse={items:Offer[]}
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export function PublishedItemsPage(){
  const {session}=useSession();const roles=session.status==='authenticated'?session.user.roles:[];const canManage=roles.includes('Owner')||roles.includes('Operator')
  const [data,setData]=useState<Response|null>(null);const [accounts,setAccounts]=useState<Account[]>([]);const [products,setProducts]=useState<Product[]>([]);const [offers,setOffers]=useState<Offer[]>([]);const [message,setMessage]=useState('')
  const [search,setSearch]=useState('');const [provider,setProvider]=useState('');const [account,setAccount]=useState('');const [channel,setChannel]=useState('');const [status,setStatus]=useState('');const [linkage,setLinkage]=useState('');const [sync,setSync]=useState('');const [page,setPage]=useState(1)
  const [editing,setEditing]=useState<Listing|null>(null);const [productId,setProductId]=useState('');const [offerId,setOfferId]=useState('')
  const load=useCallback(async()=>{const q=new URLSearchParams({page:String(page),pageSize:'20'});if(search)q.set('search',search);if(provider)q.set('provider',provider);if(account)q.set('marketplaceAccountId',account);if(channel)q.set('salesChannelId',channel);if(status)q.set('observedStatus',status);if(linkage)q.set('linkage',linkage);if(sync)q.set('syncState',sync);const r=await apiClient.get<Response>(`/api/commerce/published-items?${q}`);if(r.ok)setData(r.data);else setMessage(r.error.safeMessage)},[page,search,provider,account,channel,status,linkage,sync])
  const refs=useCallback(async()=>{const [a,p,o]=await Promise.all([apiClient.get<Account[]>('/api/commerce/marketplace-accounts'),apiClient.get<ProductResponse>('/api/products?page=1&pageSize=100'),apiClient.get<OfferResponse>('/api/commerce/offers?page=1&pageSize=100')]);if(a.ok)setAccounts(a.data);if(p.ok)setProducts(p.data.items);if(o.ok)setOffers(o.data.items)},[])
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();void refs()},0);return()=>window.clearTimeout(timer)},[load,refs])
  function edit(row:Listing){setEditing(row);setProductId(row.productId??'');setOfferId(row.channelOfferId??'')}
  async function link(){if(!editing||!productId)return;const r=await apiClient.post<void>(`/api/commerce/published-items/${editing.id}/link`,{productId,channelOfferId:offerId||null,version:editing.version});setMessage(r.ok?'Listagem vinculada.':r.error.safeMessage);if(r.ok){setEditing(null);await load()}}
  async function unlink(row:Listing){const r=await apiClient.post<void>(`/api/commerce/published-items/${row.id}/unlink?version=${row.version}`);setMessage(r.ok?'Vínculo removido.':r.error.safeMessage);if(r.ok)await load()}
  const providers=[...new Set(accounts.map(x=>x.providerCode))].sort();const channels=[...new Map([...accounts.map(x=>[x.salesChannelId,{id:x.salesChannelId,name:x.salesChannelId}] as const),...(data?.items??[]).map(x=>[x.salesChannelId,{id:x.salesChannelId,name:`${x.channelCode} · ${x.channelName}`}] as const)]).values()]
  const compatibleOffers=editing?offers.filter(x=>x.productId===productId&&x.salesChannelId===editing.salesChannelId):[]
  return <section className="product-page"><div className="page-heading"><div><Link to="/">← Início</Link><h1>Itens Publicados</h1><p>Realidade externa normalizada, sem publicação ou conexão com provedores.</p></div></div>
    <form className="card inline-form" onSubmit={e=>{e.preventDefault();setPage(1);void load()}}><label htmlFor="published-search">Buscar</label><input id="published-search" value={search} onChange={e=>setSearch(e.target.value)}/><label htmlFor="published-provider">Provedor</label><select id="published-provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Todos</option>{providers.map(x=><option key={x}>{x}</option>)}</select><label htmlFor="published-account">Conta</label><select id="published-account" value={account} onChange={e=>setAccount(e.target.value)}><option value="">Todas</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select><label htmlFor="published-channel">Canal</label><select id="published-channel" value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Todos</option>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label htmlFor="published-status">Status</label><select id="published-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{['DRAFT','ACTIVE','PAUSED','INACTIVE','ERROR'].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="published-linkage">Vínculo</label><select id="published-linkage" value={linkage} onChange={e=>setLinkage(e.target.value)}><option value="">Todos</option>{['UNLINKED','NEEDS_REVIEW','LINKED'].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="published-sync">Sincronização</label><select id="published-sync" value={sync} onChange={e=>setSync(e.target.value)}><option value="">Todos</option>{['NEVER_SYNCED','SYNCED','ERROR'].map(x=><option key={x}>{x}</option>)}</select><button type="submit">Filtrar</button></form>
    {message&&<p role="status">{message}</p>}<div className="card"><p>{data?.total??0} item(ns)</p><ul className="data-list">{data?.items.map(item=><li key={item.id}><strong>{item.title??item.externalListingId}</strong><span>{item.providerCode} · {item.accountName} · {item.channelCode}</span><span>Identidade: {item.externalSku??item.externalListingId}</span><span className="badge">{item.observedStatus}</span><span className="badge">{item.linkageState}</span><span>{item.observedPrice==null?'Preço não observado':money(item.observedPrice)}</span><span>{item.productName?`Produto: ${item.productCode} · ${item.productName}`:'Produto não vinculado'}</span><span>Oferta: {item.channelOfferId??'não vinculada'}</span><span>Sincronização: {item.syncState}; observado em {item.lastObservedAt??'desconhecido'}</span>{item.safeSyncError&&<span role="alert">{item.safeSyncError}</span>}{canManage&&<><button type="button" onClick={()=>edit(item)}>{item.linkageState==='LINKED'?'Corrigir vínculo':'Vincular'}</button>{item.linkageState==='LINKED'&&<button type="button" onClick={()=>void unlink(item)}>Desvincular</button>}</>}</li>)}</ul><div className="inline-form"><button type="button" disabled={(data?.page??1)<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Anterior</button><span>Página {data?.page??1}</span><button type="button" disabled={!data||data.page*data.pageSize>=data.total} onClick={()=>setPage(x=>x+1)}>Próxima</button></div></div>
    {editing&&canManage&&<div className="card form-stack"><h2>Vincular {editing.externalListingId}</h2><label htmlFor="link-product">Produto</label><select id="link-product" required value={productId} onChange={e=>{setProductId(e.target.value);setOfferId('')}}><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><label htmlFor="link-offer">Oferta compatível (opcional)</label><select id="link-offer" value={offerId} onChange={e=>setOfferId(e.target.value)}><option value="">Somente produto</option>{compatibleOffers.map(x=><option key={x.id} value={x.id}>{money(x.intendedUnitPrice)} · {x.status}</option>)}</select><button type="button" onClick={()=>void link()}>Confirmar vínculo</button><button type="button" onClick={()=>setEditing(null)}>Cancelar</button></div>}
  </section>
}
