import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { PublishedItemsPage } from './PublishedItemsPage'
const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}));vi.mock('../api/client',()=>({apiClient:api}))
const state=vi.hoisted(()=>({roles:['Operator'] as string[]}));vi.mock('../auth/useSession',()=>({useSession:()=>({session:{status:'authenticated',user:{roles:state.roles}}})}))
const listing={id:'l1',providerCode:'SHOPEE',marketplaceAccountId:'a1',accountName:'Loja',salesChannelId:'c1',channelCode:'SHOP',channelName:'Shopee',externalListingId:'ext-1',title:'Anúncio',observedPrice:35,observedStatus:'ACTIVE',linkageState:'UNLINKED',syncState:'NEVER_SYNCED',version:1}
function setup(){api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/published-items'))return Promise.resolve({ok:true,data:{items:[listing],page:1,pageSize:20,total:1}});if(p==='/api/commerce/marketplace-accounts')return Promise.resolve({ok:true,data:[{id:'a1',providerCode:'SHOPEE',displayName:'Loja',salesChannelId:'c1'}]});if(p.startsWith('/api/products'))return Promise.resolve({ok:true,data:{items:[{id:'p1',code:'P1',name:'Produto'}]}});if(p.startsWith('/api/commerce/offers'))return Promise.resolve({ok:true,data:{items:[]}});return Promise.resolve({ok:true,data:[]})});api.post.mockResolvedValue({ok:true,data:{}})}
describe('PublishedItemsPage',()=>{beforeEach(()=>{vi.clearAllMocks();state.roles=['Operator'];setup()})
  it('renders unlinked listing facts',async()=>{render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);expect(await screen.findByText('Anúncio')).toBeInTheDocument();expect(screen.getByText('Produto não vinculado')).toBeInTheDocument();expect(screen.queryByText('Preço não observado')).not.toBeInTheDocument()})
  it('offers product-only reconciliation to Operator',async()=>{const user=userEvent.setup();render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Vincular'}));await user.selectOptions(screen.getByLabelText('Produto'),'p1');expect(screen.getByRole('option',{name:'Somente produto'})).toBeInTheDocument()})
  it('hides reconciliation from Viewer',async()=>{state.roles=['Viewer'];render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);await screen.findByText('Anúncio');expect(screen.queryByRole('button',{name:'Vincular'})).not.toBeInTheDocument()})
  it('renders NEEDS_REVIEW as a first-class state',async()=>{api.get.mockImplementation((p:string)=>p.startsWith('/api/commerce/published-items')?Promise.resolve({ok:true,data:{items:[{...listing,linkageState:'NEEDS_REVIEW'}],page:1,pageSize:20,total:1}}):p==='/api/commerce/marketplace-accounts'?Promise.resolve({ok:true,data:[]}):p.startsWith('/api/products')?Promise.resolve({ok:true,data:{items:[]}}):Promise.resolve({ok:true,data:{items:[]}}));render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);expect(await screen.findByText('NEEDS_REVIEW')).toBeInTheDocument()})
  it('links with a compatible offer',async()=>{const user=userEvent.setup();api.get.mockImplementation((p:string)=>{if(p.startsWith('/api/commerce/published-items'))return Promise.resolve({ok:true,data:{items:[listing],page:1,pageSize:20,total:1}});if(p==='/api/commerce/marketplace-accounts')return Promise.resolve({ok:true,data:[{id:'a1',providerCode:'SHOPEE',displayName:'Loja',salesChannelId:'c1'}]});if(p.startsWith('/api/products'))return Promise.resolve({ok:true,data:{items:[{id:'p1',code:'P1',name:'Produto'}]}});return Promise.resolve({ok:true,data:{items:[{id:'o1',productId:'p1',salesChannelId:'c1',status:'ACTIVE',intendedUnitPrice:30}]}})});render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Vincular'}));await user.selectOptions(screen.getByLabelText('Produto'),'p1');await user.selectOptions(screen.getByLabelText('Oferta compatível (opcional)'),'o1');await user.click(screen.getByRole('button',{name:'Confirmar vínculo'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/published-items/l1/link',{productId:'p1',channelOfferId:'o1',version:1})})
  it('unlinks an already linked item',async()=>{const user=userEvent.setup();api.get.mockImplementation((p:string)=>p.startsWith('/api/commerce/published-items')?Promise.resolve({ok:true,data:{items:[{...listing,linkageState:'LINKED',productId:'p1',productCode:'P1',productName:'Produto'}],page:1,pageSize:20,total:1}}):p==='/api/commerce/marketplace-accounts'?Promise.resolve({ok:true,data:[]}):p.startsWith('/api/products')?Promise.resolve({ok:true,data:{items:[]}}):Promise.resolve({ok:true,data:{items:[]}}));render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Desvincular'}));expect(api.post).toHaveBeenCalledWith('/api/commerce/published-items/l1/unlink?version=1')})
  it('sends every selected filter to the server',async()=>{const user=userEvent.setup();render(<MemoryRouter><PublishedItemsPage/></MemoryRouter>);await screen.findByText('Anúncio');await user.type(screen.getByLabelText('Buscar'),'SKU');await user.selectOptions(screen.getByLabelText('Provedor'),'SHOPEE');await user.selectOptions(screen.getByLabelText('Conta'),'a1');await user.selectOptions(screen.getByLabelText('Canal'),'c1');await user.selectOptions(screen.getByLabelText('Status'),'ACTIVE');await user.selectOptions(screen.getByLabelText('Vínculo'),'UNLINKED');await user.selectOptions(screen.getByLabelText('Sincronização'),'NEVER_SYNCED');await user.click(screen.getByRole('button',{name:'Filtrar'}));await waitFor(()=>expect(api.get).toHaveBeenCalledWith(expect.stringContaining('provider=SHOPEE')));for(const fragment of ['marketplaceAccountId=a1','salesChannelId=c1','observedStatus=ACTIVE','linkage=UNLINKED','syncState=NEVER_SYNCED'])expect(api.get).toHaveBeenCalledWith(expect.stringContaining(fragment))})
})
