import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { apiClient } from '../api/client'
import { useSession } from '../auth/useSession'

type Sale = { id: string; saleNumber: string; source: string; status: string; customerNameSnapshot: string | null; salesChannelId: string; soldAt: string; netAmount: number | string; effectiveMarginPercent: number | string }
type SaleList = { items: Sale[]; page: number; pageSize: number; total: number }
type Channel = { id: string; name: string; active: boolean }
type Product = { id: string; code: string; name: string; active: boolean }
type ProductList = { items: Product[] }
const money = (value: number | string) => Number(value).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export function SalesPage() {
  const { session } = useSession(); const navigate = useNavigate(); const canManage = session.status === 'authenticated' && (session.user.roles.includes('Owner') || session.user.roles.includes('Operator'))
  const [data, setData] = useState<SaleList>({ items: [], page: 1, pageSize: 20, total: 0 }); const [channels, setChannels] = useState<Channel[]>([]); const [products, setProducts] = useState<Product[]>([])
  const [status, setStatus] = useState(''); const [filterChannel, setFilterChannel] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [message, setMessage] = useState(''); const [channelId, setChannelId] = useState(''); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState('1'); const [unitPrice, setUnitPrice] = useState(''); const [discount, setDiscount] = useState('0'); const [customer, setCustomer] = useState(''); const [shipping, setShipping] = useState('0')
  async function load(page = 1) { const query = new URLSearchParams({ page: String(page), pageSize: '20' }); if (status) query.set('status', status); if (filterChannel) query.set('channel', filterChannel); if (from) query.set('from', from); if (to) query.set('to', to); const result = await apiClient.get<SaleList>(`/api/sales?${query}`); if (result.ok) setData(result.data); else setMessage(result.error.safeMessage) }
  async function loadReferences() { const channelResult = await apiClient.get<Channel[]>('/api/sales-channels'); if (channelResult.ok) { const active = channelResult.data.filter(x => x.active); setChannels(channelResult.data); setChannelId(current => current || active[0]?.id || '') }; if (!canManage) return; const productResult = await apiClient.get<ProductList>('/api/products?page=1&pageSize=100'); if (productResult.ok) { const active = productResult.data.items.filter(x => x.active); setProducts(active); setProductId(current => current || active[0]?.id || '') } }
  // oxlint-disable-next-line react(set-state-in-effect), react-hooks/exhaustive-deps -- route filter synchronizes the server-side list.
  useEffect(() => { void load() }, [status, filterChannel, from, to])
  // oxlint-disable-next-line react(set-state-in-effect) -- reference data is fetched once for the manual-entry form.
  useEffect(() => { void loadReferences() }, [canManage])
  async function createManualSale(event: FormEvent) { event.preventDefault(); setMessage(''); const response = await apiClient.post<Sale>('/api/sales', { salesChannelId: channelId, customerId: null, customerNameSnapshot: customer || null, soldAt: null, shippingAmount: Number(shipping), notes: null, items: [{ productId, quantity: Number(quantity), unitPrice: Number(unitPrice), discountAmount: Number(discount) }] }); if (response.ok) navigate(`/sales/${response.data.id}`); else setMessage(response.error.safeMessage) }
  const lastPage = Math.max(1, Math.ceil(data.total / data.pageSize)); const channelName = (id: string) => channels.find(x => x.id === id)?.name ?? 'Canal registrado'
  return <section className="product-page"><div className="page-heading"><div><h1>Vendas</h1><p>Receita, margem e histórico comercial registrados.</p></div></div>
    <div className="split-grid"><div className="card"><div className="section-heading"><h2>Lançamentos</h2><label htmlFor="sale-status">Situação <select id="sale-status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todas</option><option value="CONFIRMED">Confirmadas</option><option value="CANCELED">Canceladas</option></select></label><label>Canal <select value={filterChannel} onChange={e => setFilterChannel(e.target.value)}><option value="">Todos</option>{channels.map(channel => <option key={channel.id} value={channel.id}>{channel.name}</option>)}</select></label><label>De <input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Até <input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></div><table><thead><tr><th>Número</th><th>Data</th><th>Cliente</th><th>Canal</th><th>Origem</th><th>Status</th><th>Receita</th><th>Margem</th></tr></thead><tbody>{data.items.map(s => <tr key={s.id}><td><Link to={`/sales/${s.id}`}>{s.saleNumber}</Link></td><td>{new Date(s.soldAt).toLocaleDateString('pt-BR')}</td><td>{s.customerNameSnapshot ?? '—'}</td><td>{channelName(s.salesChannelId)}</td><td>{s.source}</td><td><span className="badge">{s.status}</span></td><td>{money(s.netAmount)}</td><td>{(Number(s.effectiveMarginPercent) * 100).toFixed(1)}%</td></tr>)}</tbody></table><nav className="pagination"><button disabled={data.page <= 1} onClick={() => void load(data.page - 1)}>Anterior</button><span>Página {data.page} de {lastPage}</span><button disabled={data.page >= lastPage} onClick={() => void load(data.page + 1)}>Próxima</button></nav></div>
      {canManage && <form className="card form-stack" onSubmit={createManualSale}><h2>Registrar venda manual</h2><p>O custo atual, a taxa do canal, descontos e margem são calculados no servidor.</p><label>Canal de venda<select required value={channelId} onChange={e => setChannelId(e.target.value)}>{channels.filter(x => x.active).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Produto<select required value={productId} onChange={e => setProductId(e.target.value)}>{products.map(x => <option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>Quantidade<input required min="0.001" step="any" type="number" value={quantity} onChange={e => setQuantity(e.target.value)} /></label><label>Preço unitário (R$)<input required min="0.01" step="0.01" type="number" value={unitPrice} onChange={e => setUnitPrice(e.target.value)} /></label><label>Desconto unitário (R$)<input min="0" step="0.01" type="number" value={discount} onChange={e => setDiscount(e.target.value)} /></label><label>Cliente (opcional)<input value={customer} onChange={e => setCustomer(e.target.value)} /></label><label>Frete pago pelo vendedor (R$)<input min="0" step="0.01" type="number" value={shipping} onChange={e => setShipping(e.target.value)} /></label><button className="button-primary">Registrar venda</button></form>}</div>{message && <p role="status" className="form-error">{message}</p>}</section>
}
