using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Verce.Api.Authorization;
using Verce.Modules.Settings;
using Verce.Platform.Identity;
using Verce.Platform.Persistence;
using Verce.Platform.UnitOfWork;
using Verce.SharedKernel.Time;

namespace Verce.Api.Settings;

public sealed record CompanyProfileRequest(string LegalName, string TradeName, string? Document, string? Email, string? Phone, string? Website, string? Instagram, string? WhatsApp, string? ZipCode, string? Street, string? Number, string? Complement, string? District, string? City, string? State, string? Country, string? Timezone, string? Currency, long Version);
public sealed record SettingUpdateRequest(string Value, long Version);
public sealed record BrandAssetCreateRequest(string BrandAssetTypeCode, string Name);
public sealed record BrandActivationRequest(Guid VersionId, long ExpectedBrandAssetVersion);

/// <summary>M-S2-005: named response shapes. The endpoints below used to return anonymous
/// projections through untyped <c>Results.Ok</c>, which erase to <c>object</c> for OpenAPI
/// purposes — no schema, no generated frontend type. Field names are unchanged so the JSON wire
/// shape is identical to before.</summary>
public sealed record AppSettingResponse(Guid Id, string Key, string Value, AppSettingValueType ValueType, string Scope, string Description, bool IsSecret, long Version);
public sealed record BrandAssetVersionResponse(Guid Id, int VersionNumber, string ContentType, long FileSizeBytes, int WidthPx, int HeightPx, DateTimeOffset UploadedAt, bool IsCurrent);
public sealed record BrandAssetResponse(Guid Id, string BrandAssetTypeCode, string Name, bool IsActive, Guid? CurrentVersionId, long Version, IReadOnlyList<BrandAssetVersionResponse> Versions);
public sealed record BrandingLogoResponse(string Role, string Url);
public sealed record BrandingResponse(string ProductName, string ProductSubtitle, IReadOnlyList<BrandingLogoResponse> Logos);
public sealed record BrandAssetIdResponse(Guid Id);
public sealed record BrandAssetVersionUploadResponse(Guid Id, int VersionNumber, string ContentType);
/// <summary>Replaces returning the raw <see cref="CompanyProfile"/> domain entity directly:
/// that type inherits <c>PendingEvents</c> from the shared <c>Entity</c> base, which has no
/// business being serialized onto an HTTP response even though it is normally empty by the time
/// a GET observes it. A named DTO also gives OpenAPI/the generated frontend contract a schema
/// that actually matches the intended response, not incidental base-class shape.</summary>
public sealed record CompanyProfileResponse(Guid Id, string LegalName, string TradeName, string? Document, string? Email, string? Phone, string? Website, string? Instagram, string? WhatsApp, string? ZipCode, string? Street, string? Number, string? Complement, string? District, string? City, string? State, string Country, string Timezone, string Currency, long Version)
{
    public static CompanyProfileResponse From(CompanyProfile profile) => new(profile.Id, profile.LegalName, profile.TradeName, profile.Document, profile.Email, profile.Phone, profile.Website, profile.Instagram, profile.WhatsApp, profile.ZipCode, profile.Street, profile.Number, profile.Complement, profile.District, profile.City, profile.State, profile.Country, profile.Timezone, profile.Currency, profile.Version);
}

public static class SettingsEndpoints
{
    public static IEndpointRouteBuilder MapSettingsEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/settings");
        group.MapGet("/company-profile", async (VerceDbContext db, CancellationToken ct) => { var profile = await db.Set<CompanyProfile>().AsNoTracking().SingleOrDefaultAsync(ct); return profile is null ? Results.NotFound() : Results.Ok(CompanyProfileResponse.From(profile)); }).RequireAuthorization(Permissions.SettingsManage).Produces<CompanyProfileResponse>().Produces(StatusCodes.Status404NotFound);
        group.MapPut("/company-profile", async (CompanyProfileRequest request, HttpContext http, IAntiforgery anti, UserManager<ApplicationUser> users, AmbientOperationContext ambient, IUnitOfWork uow, CancellationToken ct) =>
        { if (!await Csrf(http, anti)) return Invalid(); try { var actor = await users.GetUserAsync(http.User); if (actor is null) return Results.Unauthorized(); ambient.SetActor(actor.Id, actor.DisplayName); await uow.ExecuteAsync(async (db, token) => { var profile = await db.Set<CompanyProfile>().SingleOrDefaultAsync(token); var values = new CompanyProfileValues(request.LegalName, request.TradeName, request.Document, request.Email, request.Phone, request.Website, request.Instagram, request.WhatsApp, request.ZipCode, request.Street, request.Number, request.Complement, request.District, request.City, request.State, request.Country, request.Timezone, request.Currency); if (profile is null) { if (request.Version != 0) throw new DbUpdateConcurrencyException(); db.Add(new CompanyProfile(values)); } else { if (profile.Version != request.Version) throw new DbUpdateConcurrencyException(); profile.Update(values); } }, ct); return Results.NoContent(); } catch (DbUpdateConcurrencyException) { return Conflict(); } catch (ArgumentException ex) { return Error(ex.Message); } }).RequireAuthorization(Permissions.SettingsManage);
        group.MapGet("", async (VerceDbContext db, CancellationToken ct) => Results.Ok(await db.Set<AppSetting>().AsNoTracking().OrderBy(x => x.Key).Select(x => new AppSettingResponse(x.Id, x.Key, x.Value, x.ValueType, x.Scope, x.Description, x.IsSecret, x.Version)).ToListAsync(ct))).RequireAuthorization(Permissions.SettingsManage).Produces<IReadOnlyList<AppSettingResponse>>();
        group.MapPut("/{key}", async (string key, SettingUpdateRequest request, HttpContext http, IAntiforgery anti, UserManager<ApplicationUser> users, AmbientOperationContext ambient, IUnitOfWork uow, IClock clock, CancellationToken ct) =>
        { if (!await Csrf(http, anti)) return Invalid(); try { var actor = await users.GetUserAsync(http.User); if (actor is null) return Results.Unauthorized(); ambient.SetActor(actor.Id, actor.DisplayName); await uow.ExecuteAsync(async (db, token) => { var setting = await db.Set<AppSetting>().SingleOrDefaultAsync(x => x.Key == key, token) ?? throw new KeyNotFoundException(); if (setting.Version != request.Version) throw new DbUpdateConcurrencyException(); setting.Update(request.Value, actor.Id, clock.UtcNow); }, ct); return Results.NoContent(); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (DbUpdateConcurrencyException) { return Conflict(); } catch (ArgumentException ex) { return Error(ex.Message); } }).RequireAuthorization(Permissions.SettingsManage);
        group.MapGet("/branding", async (VerceDbContext db, CancellationToken ct) =>
        { var settings = await db.Set<AppSetting>().AsNoTracking().Where(x => x.Key == "branding.product_name" || x.Key == "branding.product_subtitle").ToDictionaryAsync(x => x.Key, x => x.Value, ct); var assignments = await db.Set<BrandingAssignment>().AsNoTracking().ToListAsync(ct); var assets = await db.Set<BrandAsset>().AsNoTracking().Where(x => x.CurrentVersionId != null && x.DeletedAt == null && x.IsActive).ToListAsync(ct); var logos = assignments.Join(assets, a => a.BrandAssetId, b => b.Id, (a, b) => new BrandingLogoResponse(a.Role, $"/api/settings/brand-assets/versions/{b.CurrentVersionId}/content")).ToList(); return Results.Ok(new BrandingResponse(settings.GetValueOrDefault("branding.product_name", "VERCE 3D"), settings.GetValueOrDefault("branding.product_subtitle", "Laboratório de Custos"), logos)); }).RequireAuthorization(Permissions.CustomersRead).Produces<BrandingResponse>();
        var brand = group.MapGroup("/brand-assets").RequireAuthorization(Permissions.BrandAssetsManage);
        brand.MapGet("", async (VerceDbContext db, CancellationToken ct) => Results.Ok(await db.Set<BrandAsset>().AsNoTracking().Include(x => x.Versions).Where(x => x.DeletedAt == null).OrderBy(x => x.Name).Select(x => new BrandAssetResponse(x.Id, x.BrandAssetTypeCode, x.Name, x.IsActive, x.CurrentVersionId, x.Version, x.Versions.OrderByDescending(v => v.VersionNumber).Select(v => new BrandAssetVersionResponse(v.Id, v.VersionNumber, v.ContentType, v.FileSizeBytes, v.WidthPx, v.HeightPx, v.UploadedAt, v.IsCurrent)).ToList())).ToListAsync(ct))).Produces<IReadOnlyList<BrandAssetResponse>>();
        brand.MapPost("", async (BrandAssetCreateRequest request, HttpContext http, IAntiforgery anti, UserManager<ApplicationUser> users, AmbientOperationContext ambient, IUnitOfWork uow, CancellationToken ct) => { if (!await Csrf(http, anti)) return Invalid(); try { var actor = await users.GetUserAsync(http.User); if (actor is null) return Results.Unauthorized(); ambient.SetActor(actor.Id, actor.DisplayName); BrandAsset? asset = null; await uow.ExecuteAsync(async (db, token) => { if (!await db.Set<BrandAssetType>().AnyAsync(x => x.Code == request.BrandAssetTypeCode, token)) throw new KeyNotFoundException(); asset = new BrandAsset(request.BrandAssetTypeCode, request.Name); db.Add(asset); }, ct); return Results.Created($"/api/settings/brand-assets/{asset!.Id}", new BrandAssetIdResponse(asset!.Id)); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (ArgumentException ex) { return Error(ex.Message); } }).Produces<BrandAssetIdResponse>(StatusCodes.Status201Created);
        brand.MapPost("/{assetId:guid}/versions", async (Guid assetId, IFormFile file, HttpContext http, IAntiforgery anti, UserManager<ApplicationUser> users, AmbientOperationContext ambient, IUnitOfWork uow, IClock clock, BrandAssetStorage storage, CancellationToken ct) => { if (!await Csrf(http, anti)) return Invalid(); try { var actor = await users.GetUserAsync(http.User); if (actor is null) return Results.Unauthorized(); ambient.SetActor(actor.Id, actor.DisplayName); var stored = await storage.StoreAsync(file, ct); BrandAssetVersion? version = null; await uow.ExecuteAsync(async (db, token) => { await LockBrandAssetAsync(db, assetId, token); var asset = await db.Set<BrandAsset>().Include(x => x.Versions).SingleOrDefaultAsync(x => x.Id == assetId && x.DeletedAt == null, token) ?? throw new KeyNotFoundException(); version = asset.AddVersion(stored.Upload, actor.Id, clock.UtcNow); }, ct); return Results.Created($"/api/settings/brand-assets/versions/{version!.Id}/content", new BrandAssetVersionUploadResponse(version!.Id, version.VersionNumber, version.ContentType)); } catch (BrandAssetUploadException ex) { return Error(ex.Code); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (DbUpdateConcurrencyException) { return Conflict(); } catch (DbUpdateException ex) when (ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation }) { return Conflict(); } }).Produces<BrandAssetVersionUploadResponse>(StatusCodes.Status201Created);
        brand.MapPost("/{assetId:guid}/activate", async (Guid assetId, BrandActivationRequest request, HttpContext http, IAntiforgery anti, UserManager<ApplicationUser> users, AmbientOperationContext ambient, IUnitOfWork uow, CancellationToken ct) => { if (!await Csrf(http, anti)) return Invalid(); try { var actor = await users.GetUserAsync(http.User); if (actor is null) return Results.Unauthorized(); ambient.SetActor(actor.Id, actor.DisplayName); await uow.ExecuteAsync(async (db, token) => { await LockBrandAssetAsync(db, assetId, token); var asset = await db.Set<BrandAsset>().Include(x => x.Versions).SingleOrDefaultAsync(x => x.Id == assetId && x.DeletedAt == null, token) ?? throw new KeyNotFoundException(); if (asset.Version != request.ExpectedBrandAssetVersion) throw new DbUpdateConcurrencyException(); if (!asset.Versions.Any(x => x.Id == request.VersionId)) throw new InvalidOperationException("BRAND_ASSET_VERSION_NOT_FOUND"); await db.Set<BrandAssetVersion>().Where(x => x.BrandAssetId == assetId && x.IsCurrent).ExecuteUpdateAsync(update => update.SetProperty(x => x.IsCurrent, false), token); asset.ActivateVersion(request.VersionId); }, ct); return Results.NoContent(); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (DbUpdateConcurrencyException) { return Conflict(); } catch (DbUpdateException ex) when (ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation }) { return Conflict(); } catch (InvalidOperationException ex) { return Error(ex.Message, 404); } }).Produces(StatusCodes.Status204NoContent);
        group.MapGet("/brand-assets/versions/{versionId:guid}/content", async (Guid versionId, HttpContext http, VerceDbContext db, BrandAssetStorage storage, CancellationToken ct) => { var version = await db.Set<BrandAssetVersion>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == versionId, ct); if (version is null) return Results.NotFound(); try { var stream = await storage.OpenReadAsync(version.FilePath, ct); http.Response.Headers["X-Content-Type-Options"] = "nosniff"; return Results.File(stream, version.ContentType, enableRangeProcessing: false, lastModified: version.UploadedAt, entityTag: new Microsoft.Net.Http.Headers.EntityTagHeaderValue($"\"{version.Sha256}\"")); } catch (FileNotFoundException) { return Results.NotFound(); } }).RequireAuthorization(Permissions.CustomersRead);
        return app;
    }
    private static async Task<bool> Csrf(HttpContext context, IAntiforgery anti) { try { await anti.ValidateRequestAsync(context); return true; } catch (AntiforgeryValidationException) { return false; } }
    private static Task<int> LockBrandAssetAsync(VerceDbContext db, Guid assetId, CancellationToken cancellationToken) =>
        db.Database.ExecuteSqlInterpolatedAsync($"SELECT id FROM settings.brand_asset WHERE id = {assetId} FOR UPDATE", cancellationToken);
    private static IResult Invalid() => Results.Problem(statusCode: 400, title: "Requisição inválida."); private static IResult Conflict() => Error("CONCURRENCY_CONFLICT", 409); private static IResult Error(string code, int status = 400) => Results.Problem(statusCode: status, title: "Não foi possível concluir a operação.", extensions: new Dictionary<string, object?> { ["code"] = code });
}
