using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Verce.Platform.Persistence;

namespace Verce.Modules.Settings;

public sealed class CompanyProfileConfiguration : IEntityTypeConfiguration<CompanyProfile> { public void Configure(EntityTypeBuilder<CompanyProfile> b) { b.ToTable("company_profile", "settings", t => t.HasCheckConstraint("ck_company_profile_singleton", "id = '00000000-0000-0000-0000-000000000001'")); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.Version).IsConcurrencyToken(); b.HasApplicationMetadata(); foreach (var p in new[] { nameof(CompanyProfile.LegalName), nameof(CompanyProfile.TradeName) }) b.Property(p).HasMaxLength(200).IsRequired(); b.Property(x => x.Document).HasMaxLength(50); b.Property(x => x.Email).HasMaxLength(320); b.Property(x => x.Phone).HasMaxLength(50); b.Property(x => x.Website).HasMaxLength(2048); b.Property(x => x.Instagram).HasMaxLength(200); b.Property(x => x.WhatsApp).HasColumnName("whatsapp").HasMaxLength(50); b.Property(x => x.ZipCode).HasMaxLength(20); b.Property(x => x.Street).HasMaxLength(200); b.Property(x => x.Number).HasMaxLength(30); b.Property(x => x.Complement).HasMaxLength(200); b.Property(x => x.District).HasMaxLength(100); b.Property(x => x.City).HasMaxLength(100); b.Property(x => x.State).HasMaxLength(2); b.Property(x => x.Country).HasMaxLength(2); b.Property(x => x.Timezone).HasMaxLength(100); b.Property(x => x.Currency).HasMaxLength(3); } }
public sealed class AppSettingConfiguration : IEntityTypeConfiguration<AppSetting> { public void Configure(EntityTypeBuilder<AppSetting> b) { b.ToTable("app_setting", "settings"); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.Version).IsConcurrencyToken(); b.HasApplicationMetadata(); b.Property(x => x.Key).HasMaxLength(200).IsRequired(); b.HasIndex(x => x.Key).IsUnique(); b.Property(x => x.ValueType).HasConversion<string>().HasMaxLength(16); b.Property(x => x.Scope).HasMaxLength(100); b.Property(x => x.Description).HasMaxLength(500); } }
public sealed class BrandAssetTypeConfiguration : IEntityTypeConfiguration<BrandAssetType> { public void Configure(EntityTypeBuilder<BrandAssetType> b) { b.ToTable("brand_asset_type", "settings"); b.HasKey(x => x.Code); b.Property(x => x.Code).HasMaxLength(64); b.Property(x => x.Name).HasMaxLength(100).IsRequired(); } }
public sealed class BrandAssetConfiguration : IEntityTypeConfiguration<BrandAsset> { public void Configure(EntityTypeBuilder<BrandAsset> b) { b.ToTable("brand_asset", "settings"); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.Version).IsConcurrencyToken(); b.HasApplicationMetadata(); b.Property(x => x.BrandAssetTypeCode).HasMaxLength(64).IsRequired(); b.Property(x => x.Name).HasMaxLength(200).IsRequired(); b.HasOne<BrandAssetType>().WithMany().HasForeignKey(x => x.BrandAssetTypeCode).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Versions).WithOne().HasForeignKey(x => x.BrandAssetId).OnDelete(DeleteBehavior.Cascade); b.HasIndex(x => x.BrandAssetTypeCode).HasFilter("deleted_at IS NULL"); } }
public sealed class BrandAssetVersionConfiguration : IEntityTypeConfiguration<BrandAssetVersion> { public void Configure(EntityTypeBuilder<BrandAssetVersion> b) { b.ToTable("brand_asset_version", "settings", t => { t.HasCheckConstraint("ck_brand_asset_version_content_type", "content_type IN ('image/png', 'image/jpeg', 'image/webp')"); t.HasCheckConstraint("ck_brand_asset_version_file_size", "file_size_bytes > 0"); }); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.HasApplicationMetadata(); b.Property(x => x.FilePath).HasMaxLength(200).IsRequired(); b.Property(x => x.Sha256).HasMaxLength(64).IsRequired(); b.Property(x => x.ContentType).HasMaxLength(32).IsRequired(); b.Property(x => x.OriginalFileName).HasMaxLength(255).IsRequired(); b.HasIndex(x => new { x.BrandAssetId, x.VersionNumber }).IsUnique(); b.HasIndex(x => x.BrandAssetId).IsUnique().HasFilter("is_current"); b.HasIndex(x => x.Sha256); } }
public sealed class BrandingAssignmentConfiguration : IEntityTypeConfiguration<BrandingAssignment> { public void Configure(EntityTypeBuilder<BrandingAssignment> b) { b.ToTable("branding_assignment", "settings", t => t.HasCheckConstraint("ck_branding_assignment_role", "role IN ('SYSTEM_LOGO', 'SYSTEM_LOGO_COMPACT', 'FAVICON', 'DOCUMENT_DEFAULT_LOGO')")); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.Version).IsConcurrencyToken(); b.HasApplicationMetadata(); b.Property(x => x.Role).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.Role).IsUnique(); b.HasOne<BrandAsset>().WithMany().HasForeignKey(x => x.BrandAssetId).OnDelete(DeleteBehavior.Restrict); } }
