using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Verce.Api.Authorization;
using Verce.Api.Catalog;
using Verce.Modules.Catalog;
using Verce.Modules.Commerce;
using Verce.Modules.Costing;
using Verce.Modules.Pricing;
using Verce.Modules.Settings;
using Verce.Platform.Identity;
using Verce.Platform.Persistence;
using Verce.Platform.UnitOfWork;
using Verce.SharedKernel.Time;

namespace Verce.Api.Commerce;

public sealed record ChannelOfferWriteRequest(Guid ProductId, Guid SalesChannelId, decimal IntendedUnitPrice, ChannelOfferPriceSource PriceSource, decimal? SellerPaidShippingAmount, long? Version);
public sealed record MarketplaceAccountWriteRequest(string ProviderCode, string ExternalAccountId, Guid SalesChannelId, string DisplayName, string? CredentialReference, long? Version);
public sealed record MarketplaceListingWriteRequest(Guid MarketplaceAccountId, string ExternalListingId, string? ExternalSku, string? TitleSnapshot, decimal? ObservedPrice, MarketplaceListingStatus ObservedStatus);
public sealed record LinkListingRequest(Guid ProductId, Guid? ChannelOfferId, long Version);
public sealed record OfferResponse(Guid Id, Guid ProductId, Guid SalesChannelId, ChannelOfferStatus Status, decimal IntendedUnitPrice, ChannelOfferPriceSource PriceSource, decimal? SellerPaidShippingAmount, long Version);
public sealed record AccountCapabilityResponse(string CapabilityCode, AccountCapabilityState State);
public sealed record AccountResponse(Guid Id, string ProviderCode, string ExternalAccountId, Guid SalesChannelId, string DisplayName, bool Active, MarketplaceConnectionState ConnectionState, MarketplaceSyncState SyncState, long Version, IReadOnlyList<AccountCapabilityResponse> Capabilities);
public sealed record ListingResponse(Guid Id, Guid MarketplaceAccountId, string ExternalListingId, string? ExternalSku, string? TitleSnapshot, decimal? ObservedPrice, MarketplaceListingStatus ObservedStatus, MarketplaceLinkageState LinkageState, MarketplaceSyncState SyncState, Guid? ProductId, Guid? ChannelOfferId, long Version);
public sealed record PagedResponse<T>(IReadOnlyList<T> Items, int Page, int PageSize, int Total);
public sealed record MarketplaceAccountUpdateRequest(string DisplayName, string? CredentialReference, Guid? SalesChannelId, long Version);
public sealed record CapabilityWriteRequest(string CapabilityCode, AccountCapabilityState State, long Version);
public sealed record ObservationWriteRequest(string ObservationKey, string Fingerprint, ObservationProvenance Provenance, DateTimeOffset ProviderObservedAt, MarketplaceListingStatus ObservedStatus, decimal? ObservedPrice, long Version, string? ExternalSku = null, string? TitleSnapshot = null, string? ProviderNativeStatus = null);
public sealed record CommercialProfileImageRequest(Guid BrandAssetId, CommercialImageRole Role, int SortOrder, string? AltText, long Version);
public sealed record CommercialTagWriteRequest(string Code, string Name, bool Active, long? Version);
public sealed record ChannelEconomicsPreviewRequest(Guid ProductId, Guid SalesChannelId, decimal? IntendedUnitPrice, decimal? SellerPaidShippingAmount, int? ComparisonQuantity = null);
public sealed record ChannelEconomicsPreviewResponse(Guid ProductId, Guid SalesChannelId, decimal IntendedUnitPrice, int ComparisonQuantity, string FixedFeeApplication, string CostBasis, decimal EstimatedProductCost, decimal? PackagingComponent, decimal EstimatedCommission, decimal FixedFee, decimal? SellerPaidShippingAmount, decimal NetRevenue, decimal EstimatedProfit, decimal ContributionMargin, decimal Markup, string FeeProvenance, DateTimeOffset? FeeObservedAt, DateTimeOffset? FeeExpiresAt, string CostCoverage, string EstimateClassification, IReadOnlyList<string> MissingComponents, Guid FeeRuleId, Guid FeeRuleVersionId, Guid? PriceBracketId);

public static class CommerceEndpoints
{
    public static IEndpointRouteBuilder MapCommerceEndpoints(this IEndpointRouteBuilder app)
    {
        var group=app.MapGroup("/api/commerce");
        group.MapGet("/offers",async(VerceDbContext db,int page=1,int pageSize=25,CancellationToken ct=default)=>{var q=db.Set<ChannelOffer>().AsNoTracking().OrderBy(x=>x.ProductId).ThenBy(x=>x.SalesChannelId);var total=await q.CountAsync(ct);var rows=await q.Skip((Math.Max(page,1)-1)*Math.Clamp(pageSize,1,100)).Take(Math.Clamp(pageSize,1,100)).ToListAsync(ct);return Results.Ok(new PagedResponse<OfferResponse>(rows.Select(Offer).ToArray(),page,Math.Clamp(pageSize,1,100),total));}).RequireAuthorization(Permissions.CommerceRead);
        group.MapPost("/offers",async(ChannelOfferWriteRequest r,HttpContext h,IAntiforgery csrf,UserManager<ApplicationUser> users,AmbientOperationContext ambient,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Problem("ANTIFORGERY_VALIDATION_FAILED",400);OfferResponse? result=null;try{await uow.ExecuteAsync(async(db,t)=>{var actor=await users.GetUserAsync(h.User);if(actor is null)throw new UnauthorizedAccessException();ambient.SetActor(actor.Id,actor.DisplayName);if(!await db.Set<Product>().AnyAsync(x=>x.Id==r.ProductId,t)||!await db.Set<SalesChannel>().AnyAsync(x=>x.Id==r.SalesChannelId,t))throw new ArgumentException("CHANNEL_OFFER_REFERENCE_NOT_FOUND");var entity=new ChannelOffer(r.ProductId,r.SalesChannelId,r.IntendedUnitPrice,r.PriceSource,r.SellerPaidShippingAmount);db.Add(entity);result=Offer(entity);},ct);return Results.Created($"/api/commerce/offers/{result!.Id}",result);}catch(ArgumentException ex){return Problem(ex.Message,422);}catch(DbUpdateException){return Problem("CHANNEL_OFFER_ALREADY_EXISTS",409);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapPut("/offers/{id:guid}",async(Guid id,ChannelOfferWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var e=await db.Set<ChannelOffer>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(r.Version!=e.Version)throw new InvalidOperationException("CONCURRENCY_CONFLICT");e.SetCommercialTerms(r.IntendedUnitPrice,r.PriceSource,r.SellerPaidShippingAmount);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapPost("/offers/{id:guid}/{action}",async(Guid id,string action,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var e=await db.Set<ChannelOffer>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(e.Version!=version)throw new InvalidOperationException();if(action=="activate"){var productActive=await db.Set<Product>().AnyAsync(x=>x.Id==e.ProductId&&x.Active,t);var channelActive=await db.Set<SalesChannel>().AnyAsync(x=>x.Id==e.SalesChannelId&&x.Active,t);if(!productActive||!channelActive)throw new ArgumentException("CHANNEL_OFFER_ACTIVATION_REFERENCE_INACTIVE");e.Activate(DateTimeOffset.UtcNow);}else if(action=="deactivate")e.Deactivate(DateTimeOffset.UtcNow);else throw new ArgumentException("COMMERCE_ACTION_INVALID");},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapGet("/marketplace-accounts",async(VerceDbContext db,CancellationToken ct)=>Results.Ok((await db.Set<MarketplaceAccount>().AsNoTracking().Include(x=>x.Capabilities).OrderBy(x=>x.DisplayName).ToListAsync(ct)).Select(Account).ToArray())).RequireAuthorization(Permissions.CommerceRead);
        group.MapGet("/providers",async(VerceDbContext db,CancellationToken ct)=>Results.Ok(await db.Set<MarketplaceProvider>().AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Code,x.Name,capabilities=db.Set<MarketplaceProviderCapability>().Where(c=>c.ProviderCode==x.Code).OrderBy(c=>c.CapabilityCode).Select(c=>new{c.CapabilityCode,c.State}).ToArray()}).ToListAsync(ct))).RequireAuthorization(Permissions.CommerceRead);
        group.MapGet("/product-image-assets",async(VerceDbContext db,CancellationToken ct)=>Results.Ok(await db.Set<BrandAsset>().AsNoTracking().Where(x=>x.BrandAssetTypeCode=="PRODUCT_IMAGE"&&x.IsActive&&x.DeletedAt==null&&x.CurrentVersionId!=null).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name,x.CurrentVersionId,url=$"/api/settings/brand-assets/versions/{x.CurrentVersionId}/content"}).ToListAsync(ct))).RequireAuthorization(Permissions.CommerceRead);
        group.MapPost("/marketplace-accounts",async(MarketplaceAccountWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var channel=await db.Set<SalesChannel>().SingleOrDefaultAsync(x=>x.Id==r.SalesChannelId,t);if(channel is null||!channel.Active||channel.Kind!=SalesChannelKind.Marketplace||channel.Code==SalesChannel.DirectChannelCode)throw new ArgumentException("MARKETPLACE_ACCOUNT_CHANNEL_INVALID");if(!await db.Set<MarketplaceProvider>().AnyAsync(x=>x.Code==r.ProviderCode,t))throw new ArgumentException("MARKETPLACE_PROVIDER_NOT_FOUND");db.Add(new MarketplaceAccount(r.ProviderCode,r.ExternalAccountId,r.SalesChannelId,r.DisplayName,r.CredentialReference));},ct);return Results.NoContent();}catch(ArgumentException ex){return Problem(ex.Message,422);}catch(DbUpdateException){return Problem("MARKETPLACE_ACCOUNT_ALREADY_EXISTS",409);}}).RequireAuthorization(Permissions.CommerceAccountsManage);
        group.MapGet("/published-items", CommerceReadModels.PublishedItemsAsync).RequireAuthorization(Permissions.CommerceRead);
        group.MapPost("/published-items",async(MarketplaceListingWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{if(!await db.Set<MarketplaceAccount>().AnyAsync(x=>x.Id==r.MarketplaceAccountId,t))throw new ArgumentException("MARKETPLACE_ACCOUNT_NOT_FOUND");db.Add(new MarketplaceListing(r.MarketplaceAccountId,r.ExternalListingId,r.ExternalSku,r.ObservedStatus,r.TitleSnapshot,r.ObservedPrice));},ct);return Results.NoContent();}catch(ArgumentException ex){return Problem(ex.Message,422);}catch(DbUpdateException){return Problem("MARKETPLACE_LISTING_ALREADY_EXISTS",409);}}).RequireAuthorization(Permissions.CommerceAccountsManage);
        group.MapPost("/published-items/{id:guid}/link",(Guid id,LinkListingRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>Link(id,r,h,csrf,uow,ct)).RequireAuthorization(Permissions.CommerceManage);
        group.MapPost("/published-items/{id:guid}/unlink",async(Guid id,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var l=await db.Set<MarketplaceListing>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(l.Version!=version)throw new InvalidOperationException();l.Unlink();},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapGet("/catalog", CommerceReadModels.CatalogAsync).RequireAuthorization(Permissions.CommerceRead);
        // Account credentials are deliberately represented only by an opaque reference.  The
        // read DTO above does not expose it, and channel reassignment is rejected by the root.
        group.MapPut("/marketplace-accounts/{id:guid}",async(Guid id,MarketplaceAccountUpdateRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var a=await db.Set<MarketplaceAccount>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(a.Version!=r.Version)throw new InvalidOperationException();if(r.SalesChannelId is { } channel)a.RejectSalesChannelReassignment(channel);a.Update(r.DisplayName,r.CredentialReference);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceAccountsManage);
        group.MapPost("/marketplace-accounts/{id:guid}/{action}",async(Guid id,string action,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var a=await db.Set<MarketplaceAccount>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(a.Version!=version)throw new InvalidOperationException();if(action=="activate")a.Activate();else if(action=="deactivate")a.Deactivate();else throw new ArgumentException("COMMERCE_ACTION_INVALID");},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceAccountsManage);
        group.MapPost("/marketplace-accounts/{id:guid}/capabilities",async(Guid id,CapabilityWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var a=await db.Set<MarketplaceAccount>().Include(x=>x.Capabilities).SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(a.Version!=r.Version)throw new InvalidOperationException();a.SetCapability(r.CapabilityCode,r.State);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceAccountsManage);
        group.MapPost("/published-items/{id:guid}/observations",async(Guid id,ObservationWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var l=await db.Set<MarketplaceListing>().Include(x=>x.Observations).SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(l.Version!=r.Version)throw new InvalidOperationException();l.ApplyObservation(r.ObservationKey,r.Fingerprint,r.Provenance,r.ProviderObservedAt,DateTimeOffset.UtcNow,r.ObservedStatus,r.ObservedPrice,r.ExternalSku,r.TitleSnapshot,r.ProviderNativeStatus);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapGet("/tags",async(VerceDbContext db,CancellationToken ct)=>Results.Ok(await db.Set<CommercialTag>().AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.Active,x.Version}).ToListAsync(ct))).RequireAuthorization(Permissions.CommerceRead);
        group.MapPost("/tags",async(CommercialTagWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync((db,t)=>{var tag=new CommercialTag(r.Code,r.Name);tag.Update(r.Name,r.Active);db.Add(tag);return Task.CompletedTask;},ct);return Results.NoContent();}catch(ArgumentException ex){return Problem(ex.Message,422);}catch(DbUpdateException){return Problem("COMMERCIAL_TAG_ALREADY_EXISTS",409);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapPut("/tags/{id:guid}",async(Guid id,CommercialTagWriteRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var tag=await db.Set<CommercialTag>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(tag.Version!=r.Version)throw new InvalidOperationException();tag.Update(r.Name,r.Active);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapGet("/profiles/{productId:guid}",async(Guid productId,VerceDbContext db,CancellationToken ct)=>{var p=await db.Set<ProductCommercialProfile>().AsNoTracking().Include(x=>x.Images).Include(x=>x.Tags).SingleOrDefaultAsync(x=>x.ProductId==productId,ct);return p is null?Results.NotFound():Results.Ok(new{p.Id,p.ProductId,p.Version,images=p.Images.OrderBy(x=>x.SortOrder).Select(x=>new{x.Id,x.BrandAssetId,x.Role,x.SortOrder,x.AltText}),tagIds=p.Tags.Select(x=>x.CommercialTagId)});}).RequireAuthorization(Permissions.CommerceRead);
        group.MapPost("/profiles/{productId:guid}/images",async(Guid productId,CommercialProfileImageRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{if(!await db.Set<Product>().AnyAsync(x=>x.Id==productId,t))throw new ArgumentException("COMMERCIAL_PROFILE_PRODUCT_NOT_FOUND");if(!await db.Set<BrandAsset>().AnyAsync(x=>x.Id==r.BrandAssetId&&x.BrandAssetTypeCode=="PRODUCT_IMAGE"&&x.IsActive&&x.DeletedAt==null&&x.CurrentVersionId!=null,t))throw new ArgumentException("COMMERCIAL_IMAGE_ASSET_INVALID");var p=await db.Set<ProductCommercialProfile>().Include(x=>x.Images).SingleOrDefaultAsync(x=>x.ProductId==productId,t);if(p is null){if(r.Version!=0)throw new InvalidOperationException();p=new ProductCommercialProfile(productId);db.Add(p);}else if(p.Version!=r.Version)throw new InvalidOperationException();p.AddImage(r.BrandAssetId,r.Role,r.SortOrder,r.AltText);},ct);return Results.NoContent();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapDelete("/profiles/{productId:guid}/images/{imageId:guid}",async(Guid productId,Guid imageId,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var p=await db.Set<ProductCommercialProfile>().Include(x=>x.Images).SingleOrDefaultAsync(x=>x.ProductId==productId,t)??throw new KeyNotFoundException();if(p.Version!=version)throw new InvalidOperationException("CONCURRENCY_CONFLICT");p.RemoveImage(imageId);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException ex)when(ex.Message=="CONCURRENCY_CONFLICT"){return Problem(ex.Message,409);}catch(InvalidOperationException ex){return Problem(ex.Message,404);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapPost("/profiles/{productId:guid}/tags/{tagId:guid}",async(Guid productId,Guid tagId,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{if(!await db.Set<Product>().AnyAsync(x=>x.Id==productId,t))throw new ArgumentException("COMMERCIAL_PROFILE_PRODUCT_NOT_FOUND");var p=await db.Set<ProductCommercialProfile>().Include(x=>x.Tags).SingleOrDefaultAsync(x=>x.ProductId==productId,t);if(p is null){if(version!=0)throw new InvalidOperationException();p=new ProductCommercialProfile(productId);db.Add(p);}else if(p.Version!=version)throw new InvalidOperationException();if(!await db.Set<CommercialTag>().AnyAsync(x=>x.Id==tagId&&x.Active,t))throw new ArgumentException("COMMERCIAL_TAG_NOT_FOUND");p.AssignTag(tagId);},ct);return Results.NoContent();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapDelete("/profiles/{productId:guid}/tags/{tagId:guid}",async(Guid productId,Guid tagId,long version,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct)=>{if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var p=await db.Set<ProductCommercialProfile>().Include(x=>x.Tags).SingleOrDefaultAsync(x=>x.ProductId==productId,t)??throw new KeyNotFoundException();if(p.Version!=version)throw new InvalidOperationException();p.RemoveTag(tagId);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}}).RequireAuthorization(Permissions.CommerceManage);
        group.MapPost("/channel-economics/preview", async (ChannelEconomicsPreviewRequest r, HttpContext h, IAntiforgery csrf, VerceDbContext db, ICostingInventoryReader inventory, AppSettingValueReader settings, IClock clock, IChannelFeeProvider fees, CancellationToken ct) =>
        {
            if (!await Csrf(h, csrf)) return Results.BadRequest();
            var quantity = r.ComparisonQuantity ?? 1;
            if (quantity < 1) return Problem("COMPARISON_QUANTITY_INVALID", 422);
            var product = await ProductEndpoints.LoadProductAsync(db, r.ProductId, ct);
            if (product is null) return Problem("PRODUCT_NOT_FOUND", 404);
            var channel = await db.Set<SalesChannel>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == r.SalesChannelId && x.Active, ct);
            if (channel is null) return Problem("SALES_CHANNEL_NOT_FOUND", 422);
            CostCalculationResult cost;
            try { cost = await ProductCostCalculator.CalculateAsync(product, inventory, settings, ct); }
            catch (ArgumentException ex) { return Problem(ex.Message, 422); }
            var offer = await db.Set<ChannelOffer>().AsNoTracking().SingleOrDefaultAsync(x => x.ProductId == r.ProductId && x.SalesChannelId == r.SalesChannelId, ct);
            var price = r.IntendedUnitPrice ?? offer?.IntendedUnitPrice;
            if (price is null || price <= 0) return Problem("CHANNEL_OFFER_PRICE_REQUIRED", 422);
            var quote = await fees.ResolveAsync(r.SalesChannelId, price.Value, clock.OrganizationToday(), ct);
            if (quote is null) return Problem("FEE_RULE_NOT_FOUND", 422);
            var margin = channel.DefaultMarginPercent ?? await settings.GetDecimalAsync("pricing.default_margin_percent", ct);
            var rounding = Enum.TryParse<PriceRoundingPolicy>(await settings.GetStringAsync("pricing.price_rounding_policy", ct), out var configured) ? configured : throw new InvalidOperationException("SETTING_VALUE_INVALID");
            var denominator = await settings.GetDecimalAsync("pricing.margin_warning_denominator", ct);
            var pricing = CommercialPricingEngine.Calculate(new CommercialPricingInput(cost.Totals.EstimatedUnitCost, margin, rounding, denominator, price, CommercialDiscountKind.None, 0m, quote.CommissionPercent, quote.FixedFee, quote.MinimumFee, quote.MaximumFee, []));
            if (pricing.IsFailure) return Problem(pricing.ErrorCode!, 422);
            var fixedFee = quote.FixedFeeApplication == "PER_ORDER" ? Verce.SharedKernel.Rounding.ToInternal(quote.FixedFee / quantity) : quote.FixedFee;
            var shipping = r.SellerPaidShippingAmount ?? offer?.SellerPaidShippingAmount;
            if (shipping < 0) return Problem("CHANNEL_OFFER_SHIPPING_INVALID", 422);
            var net = Verce.SharedKernel.Rounding.ToMoney(pricing.Value.NetUnitPrice - pricing.Value.CommissionAmount - fixedFee - (shipping ?? 0m));
            var profit = Verce.SharedKernel.Rounding.ToMoney(net - cost.Totals.EstimatedUnitCost);
            var missing = new List<string> { "ENERGY_UNAVAILABLE" };
            if (shipping is null) missing.Add("SHIPPING");
            return Results.Ok(new ChannelEconomicsPreviewResponse(r.ProductId, r.SalesChannelId, pricing.Value.UnitPrice, quantity, quote.FixedFeeApplication, "ESTIMATED", cost.Totals.EstimatedUnitCost, null, pricing.Value.CommissionAmount, fixedFee, shipping, net, profit, price == 0 ? 0 : Verce.SharedKernel.Rounding.ToPercent(profit / price.Value), cost.Totals.EstimatedUnitCost == 0 ? 0 : Verce.SharedKernel.Rounding.ToPercent(price.Value / cost.Totals.EstimatedUnitCost - 1m), quote.Provenance, quote.ObservedAt, quote.ExpiresAt, "PARTIAL", "PARTIAL_ESTIMATE", missing, quote.FeeRuleId, quote.FeeRuleVersionId, quote.PriceBracketId));
        }).RequireAuthorization(Permissions.CommerceRead);
        return app;
    }
    private static async Task<IResult> Link(Guid id,LinkListingRequest r,HttpContext h,IAntiforgery csrf,IUnitOfWork uow,CancellationToken ct){if(!await Csrf(h,csrf))return Results.BadRequest();try{await uow.ExecuteAsync(async(db,t)=>{var listing=await db.Set<MarketplaceListing>().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(listing.Version!=r.Version)throw new InvalidOperationException();if(!await db.Set<Product>().AnyAsync(x=>x.Id==r.ProductId,t))throw new ArgumentException("LISTING_PRODUCT_NOT_FOUND");var account=await db.Set<MarketplaceAccount>().SingleAsync(x=>x.Id==listing.MarketplaceAccountId,t);ChannelOffer? offer=r.ChannelOfferId is null?null:await db.Set<ChannelOffer>().SingleOrDefaultAsync(x=>x.Id==r.ChannelOfferId,t);if(r.ChannelOfferId is not null&&offer is null)throw new ArgumentException("LISTING_OFFER_NOT_FOUND");listing.Link(r.ProductId,r.ChannelOfferId,offer?.ProductId,offer?.SalesChannelId,account.SalesChannelId);},ct);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException){return Problem("CONCURRENCY_CONFLICT",409);}catch(ArgumentException ex){return Problem(ex.Message,422);}}
    private static OfferResponse Offer(ChannelOffer x)=>new(x.Id,x.ProductId,x.SalesChannelId,x.Status,x.IntendedUnitPrice,x.PriceSource,x.SellerPaidShippingAmount,x.Version); private static AccountResponse Account(MarketplaceAccount x)=>new(x.Id,x.ProviderCode,x.ExternalAccountId,x.SalesChannelId,x.DisplayName,x.Active,x.ConnectionState,x.SyncState,x.Version,x.Capabilities.Select(c=>new AccountCapabilityResponse(c.CapabilityCode,c.State)).ToArray()); private static ListingResponse Listing(MarketplaceListing x)=>new(x.Id,x.MarketplaceAccountId,x.ExternalListingId,x.ExternalSku,x.TitleSnapshot,x.ObservedPrice,x.ObservedStatus,x.LinkageState,x.SyncState,x.ProductId,x.ChannelOfferId,x.Version); private static async Task<bool> Csrf(HttpContext h,IAntiforgery a){try{await a.ValidateRequestAsync(h);return true;}catch(AntiforgeryValidationException){return false;}} private static IResult Problem(string code,int status)=>Results.Problem(statusCode:status,title:code);
}
